### ISSUE TITLE
Feature request: Open files with xdg-open by default

### ISSUE THREAD

**Issue by cjbassi** [kamiyaa/joshuto#1]
When trying to open a file that doesn't have an entry in the `mimetype.toml`, joshuto outputs `Don't know how to open file :(`, but I think it would be good to instead open the file with `xdg-open` on Linux and `open` on Mac.

Also, just wanted to say this project looks really exciting and great so far!

**Comment by kamiyaa** [comment]
Thanks! Won't be as active anymore because back to school. But right now, I'm focused on trying to get readline like abilities when asking for user input. So text can be auto-completed
