### ISSUE TITLE
[Feature Request] Dynamic Columns (Pans) configured from the joshuto.toml file

### ISSUE THREAD

**Issue by GwakaMolie** [kamiyaa/joshuto#104]
Ranger has the ability to change the number of pans, I took a look at the code and it seems that layout is hard coded am relatively new to rust, but I will try to add this in.

**Comment by kamiyaa** [comment]
Can you provide some more details?
i.e. a screenshot would be nice and what specific options to enable them in ranger.
Thanks!

**Comment by GwakaMolie** [comment]
### This is how ranger configure the number of columns
https://github.com/ranger/ranger/blob/c4e732b8045c4be1e001b4de3750524498ceaa44/ranger/config/rc.conf#L29-L30

- Setting `column_ratios` to `1,3,4` will look like this: 

![rangerC3](https://user-images.githubusercontent.com/54556509/141933820-e7a9a5db-4ce8-44f7-8703-d4d7150c0057.png)

- Setting `column_ratios` to `2,2` will look like this: 

![rangerC2](https://user-images.githubusercontent.com/54556509/141933743-6d04c8b6-168a-4175-ae36-0dd1c0ebe258.png)
