### ISSUE TITLE
Featured request: show terminal and hide joshuto by some keymap

### ISSUE THREAD

**Issue by adanilovich** [kamiyaa/joshuto#107]
Hi there, I'd like to propose the feature, which could hide joshuto file manager and display terminal for working using bash|zsh|fish console commands in current directory. The feature has been working in my ranger setup by shift + s keymap.

**Comment by kamiyaa** [comment]
Joshuto has the feature of exiting into the current directory (You can find [here](https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md#general) `quit_to_cwd`).
Does that work with your workflow? Or do you have a need for joshuto to continue running in the background while executing shell commands?

**Comment by adanilovich** [comment]
It's awesome! It's working for me with some fix in to bash script. Just added mkdir and touch commands to create temporary file. 

Sure, it would be nice that joshua can work in background. Because, in such case we could be work with several tabs, hide joshuto and continue work with them after restore.

**Comment by kamiyaa** [comment]
Awesome!
