### ISSUE TITLE
[Feature Request] scroll preview

### ISSUE THREAD

**Issue by kennycallado** [kamiyaa/joshuto#108]
Hi,
It's just an idea, but now that joshuto supports previews and syntax highlighting, it will be an awesome feature to be able to scroll through the preview with '{' and '}' like '[' ']' is used to change the folder from the first column.

**Comment by kamiyaa** [comment]
Closed via 186e9a1f9efcb3832a2e3deff8243d8e9c4de6b2

You can use `preview_cursor_move_up` and `preview_cursor_move_down` :)
