### ISSUE TITLE
Improve Documentation (Love the Project)

### ISSUE THREAD

**Issue by sagedemage** [kamiyaa/joshuto#116]
I was able to compile joshuto on Debian 11 (stable). I had to install a new version of the rust compiler (rustc) on Debian 11 (stable) for it to work. The problem was that Debian 11 (stable) was using rustc version 1.48.0. I installed rustc version 1.57.0 to get the program to compile. Under dependencies in the Read Me, it is a good idea to mention the version of rustc you used to compile joshuto. Great job on the project :).

**Comment by kamiyaa** [comment]
Thank you!

Added in ca0bdc642888eaf06402771bae3e9d9433c03876
