### ISSUE TITLE
Implement Continuous Scrolling

### ISSUE THREAD

**Issue by DLFW** [kamiyaa/joshuto#117]
When dir lists are longer than the visible area, Joshuto provides some “paging” behavior: When crossing the upper or lower border of a visible dir list with the cursor, Joshuto ”turns the page” and shows the next _n_ entries.

This is different from the behavior of most other programs, including ranger and lf, where the list of entries is continuously scrolled when the cursor reaches or comes close to the relevant border. Ranger has this distance from where the programs moves the list instead of the cursor [configurable](https://github.com/ranger/ranger/blob/8181077f3b0afc7b6258a85d3a03b7bce23d316c/ranger/config/rc.conf#L205).

This scrolling behavior has some advantages: Eyes don't have to jump when the “page turns”, one can always see the surrounding files when checking a list of files and so on.

This behavior should be implemented for Joshuto.

Proposal: Introduce a configuration parameter like ranger. If it's specified, behave like ranger, if not, use the current paging strategy.

If there are no obligations, I would pick this up myself ;)

**Comment by DLFW** [comment]
I just saw that there is already [a scroll_offset configuration option](https://github.com/kamiyaa/joshuto/blob/7791f93d95d350bdbb8dbdde4a9ec6fcbd32df41/config/joshuto.toml#L9) and a struct variable [`viewport_index` in `JoshutoDirList`](https://github.com/kamiyaa/joshuto/blob/7791f93d95d350bdbb8dbdde4a9ec6fcbd32df41/config/joshuto.toml#L9). I also saw the comment in the doc that this option does currently not work.

Is it correct that this is basically dead code? Was the idea to remove the current “paging strategy” completely?

**Comment by kamiyaa** [comment]
> Is it correct that this is basically dead code? Was the idea to remove the current “paging strategy” completely?

Yep, the original design was to follow ranger's behaviour but I ended up settling with this solution because it was a bit hard to get working. So these options are basically dead code.

But I guess now we can add more functions to calculate the terminal/windows sizes and stuff to figure out where the offset should be and everything and then modify a `offset_index` when we modify the regular `index` in `cursor_move.rs`, `parent_cursor_move.rs` etc.

**Comment by DLFW** [comment]
Provided #118.

BTW: This would now also allow to implement a "buffer scrolling" like in VIM, where the user scroll the content without moving the cursor. If the user just wants to peek through the dir content, that can be faster as the cursor does not need to be navigated to the other end first. But that's another story...

**Comment by kamiyaa** [comment]
Closed via https://github.com/kamiyaa/joshuto/pull/118
