### ISSUE TITLE
Does a custom mimetype-config inherit from the default config?

### ISSUE THREAD

**Issue by hoijui** [kamiyaa/joshuto#119]
... or would I have to copy paste the default config, and continue from there?

Would it be ok to include this info in the doc about mimetype.toml?

**Comment by kamiyaa** [comment]
You would need to copy paste it :+1: 
Yeah we can include it.

**Comment by kamiyaa** [comment]
Closed via f3a42a66f054879b0450260c63ee3587a955cc78

**Comment by hoijui** [comment]
Perfect!! thank you @kamiyaa! :-)
