### ISSUE TITLE
Remove ueberzug image preview on help page

### ISSUE THREAD

**Issue by krivahtoo** [kamiyaa/joshuto#123]
Currently, image previews are shown when you open the help page while a preview is active.

![2022-01-12-203431_564x340_scrot](https://user-images.githubusercontent.com/41364823/149193027-79c3e047-51ce-4892-b48b-47edd858d8ed.png)

**Comment by DLFW** [comment]
Provided a quick fix in #125.

**Comment by DLFW** [comment]
Fix has been merged. I guess we can close this. :)
