### ISSUE TITLE
Subprocess while still being able to use the file manager

### ISSUE THREAD

**Issue by Mythbusters123** [kamiyaa/joshuto#129]
Whenever I play an MP3, it spawns MPV but give me the STDOUT of MPV instead of showing me the file manager, which means i cannot do any work while playing an MP3 or doing anything with a GUI it shows the STDOUT of that application. I get that this could be useful for when you are using a TTY or just dont want to open GUI apps, but I think that an option (either cmdline or in joshuto.toml) could be greatly appreciated here.

**Comment by kamiyaa** [comment]
Are you talking about the `fork` option? This makes the process spawn in the background and sends all output to /dev/null

Example: https://github.com/kamiyaa/joshuto/blob/main/config/mimetype.toml#L15

**Comment by Mythbusters123** [comment]
Oh, thank you so much :)

**Comment by kamiyaa** [comment]
> Oh, thank you so much :). Would be nice to enable this globally for everything though

Nah we need it like this for opening files with terminal applications. In which, we want joshuto to stop listening for input or else it will steal input from the terminal application. Ranger follows a similar pattern as well in their `rifle.conf` I believe

**Comment by Mythbusters123** [comment]
You could have an "exclude" category in a config file, but I completely understand.
