### ISSUE TITLE
[Feature Request] Interactive search

### ISSUE THREAD

**Issue by sushi-shi** [kamiyaa/joshuto#138]
Good day!

I would want to implement an interactive search, as I miss it so much after switching from Ranger.
Here is an [example](https://github.com/sushi-shi/test/blob/master/out.gif).

I tried to [implement](https://github.com/sushi-shi/joshuto/commit/c640cd22c21140eec5405cc89b5ab2d48b53936a) it by making an iterator (kind of), which returns `String` from the current `line_buffer`, parses it and runs `search_string` if the command matches. 
Sadly, after that I realized that this iterator mutably borrows `AppContext` and `search_string` also needs to mutably borrow it.
So it doesn't work... (Also it is a bit wasteful, as it needs to `clone` on each key press). I _can_ make this approach work by wrapping required fields into `Rc<RefCell<_>>` but it doesn't feel like a good solution. As another solution, I think, I can add a callback, which `read_and_execute` and `user_input` functions will accept and call whenever `line_buffer` changes, it feels like it should work, however, before I proceed I would like to ask for your opinion first.

Thank you for making such a nice tool!

**Comment by sushi-shi** [comment]
Also it feels like a `:command [args]` string shouldn't be a command and can be parsed elsewhere. It would also allow to autocomplete commands (which is the next thing I want to tackle)

**Comment by kamiyaa** [comment]
What do you mean by interactive search?

Also yeah, I'm fine with `:command` not being a command and being parsed elsewhere

**Comment by sushi-shi** [comment]
Being able to search as you type!

**Comment by kamiyaa** [comment]
I think interactive search can already be done via fzf or are you thinking of something else?

**Comment by sushi-shi** [comment]
As I write a search pattern I want joshuto to interactively (i.e. without press Enter) select the first best match. I did write a small PR which implements it

**Comment by kamiyaa** [comment]
> As I write a search pattern I want joshuto to interactively (i.e. without press Enter) select the first best match. I did write a small PR which implements it

Ah I see, that makes sense. Will this conflict with the line number code?
https://github.com/kamiyaa/joshuto/commit/5f7bd3889dfc054308c19f655aa951946cfb299c

Where you can start typing numbers to move the cursor.

**Comment by kamiyaa** [comment]
Closing via https://github.com/kamiyaa/joshuto/pull/140
