### ISSUE TITLE
theme.toml does not parse hex colors

### ISSUE THREAD

**Issue by Beethoven-n** [kamiyaa/joshuto#151]
`str_to_color()` [in style.rs](https://github.com/kamiyaa/joshuto/blob/18d4a4c8a7c5060ed0f5094c958afe4f800e91d4/src/config/theme/style.rs#L64) only has a method to parse Rgb values, when colors_transform has methods to convert hex colors into Rgb colors.

Before the Rgb parsing, it should be possible to convert a hex color into an Rgb with `rgb.from_hex_str`, then pass that into the Rgb parsing method. (there's probably a better way to do that)

**Comment by kamiyaa** [comment]
Shouldn't be too hard to implement. But currently, I'm a bit busy and probably won't get around to working on this at the moment

**Comment by Beethoven-n** [comment]
would've done a pull request about it if i was comfortable enough with rust to know that the way i thought it should be done was the correct way

**Comment by kamiyaa** [comment]
Closed via https://github.com/kamiyaa/joshuto/pull/154
