### ISSUE TITLE
Plaintext files with no extension resort to open_with command, etc.

### ISSUE THREAD

**Issue by Beethoven-n** [kamiyaa/joshuto#153]
i can apparently only open non-extensioned files with an open_with command, (or xdg-open, depending on the file)
![image](https://user-images.githubusercontent.com/44652883/156472386-d1f25fb5-0a7e-4724-93f9-9f4b64adc1ee.png)

non-extensioned plaintext files also can't be specified in mimetype.toml for some reason? attempting `plain.inherit = "text_default"` does nothing

**Comment by kamiyaa** [comment]
Yes, this has not been implemented yet.

Currently joshuto just checks for the file extension when opening files and if there is no file extension, it will fallback to `open_with`.

Off the top of my head, there are 2 possible solutions here:
1. Have an entry in `mimetype.toml` for fallback (ie. no extension)
2. Upon `open`, try to somehow parse the type of the file (either through a library or getting the output of a command like `file`), and figure out its mimetype and then we can have a section for mimetypes in `mimetype.toml`

**Comment by Beethoven-n** [comment]
honestly just having a "plain" entry should do it, because files like these are reported as `text/plain` by `xdg-mime query filetype`

**Comment by kamiyaa** [comment]
This should be implemented now.
See https://github.com/kamiyaa/joshuto/issues/200
