### ISSUE TITLE
failed to download `tui v0.17.0`

### ISSUE THREAD

**Issue by mohamadali-halwani** [kamiyaa/joshuto#155]
Unable to build joshuto and it gives me this error:
```
Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.17.0/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.`
```

I'm on debian 11 `5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux` and I have cargo and rust installed

**Comment by kamiyaa** [comment]
What version of cargo and rust are you using?
```
~$ cargo --version
~$ rustc --version
```

**Comment by mohamadali-halwani** [comment]
`cargo 1.46.0`
`rustc 1.48.0`
I think they are the latest versions on Debian, right?

**Comment by mohamadali-halwani** [comment]
What should I do to further debug this issue?

**Comment by kamiyaa** [comment]
Hey, your cargo and rust version is too old. Joshuto requires rust/cargo 1.55+

**Comment by kamiyaa** [comment]
One solution to get it working on your system is by installing rust and cargo via https://rustup.rs/

**Comment by mohamadali-halwani** [comment]
Alright, thanks for your help.
