### ISSUE TITLE
Should we use v before the version number in tags?

### ISSUE THREAD

**Issue by kennycallado** [kamiyaa/joshuto#159]
Hi!

I'm working on PR #102 and I was wondering if we should start using v before the version number when tag a version. It's almost an standard and could be one of the problem why PR #102 doesn't work.

Reference to semantic versioning:
https://semver.org/#is-v123-a-semantic-version

I have checked different ways...
https://github.com/kennycallado/joshuto-1/releases

**Comment by kamiyaa** [comment]
Yeah, switching to v0.x.y is fine with me

**Comment by kamiyaa** [comment]
Closing via https://github.com/kamiyaa/joshuto/pull/160 ?
