### ISSUE TITLE
Implement vims `H`, `L` and `M` actions

### ISSUE THREAD

**Issue by peb-adr** [kamiyaa/joshuto#164]
I like to use this programm.

But I use the `<Shift-h>`,  `<Shift-L>` and `<Shift-m>` key presses alot in vim to get to the top/bottom/middle of the current view quickly.
It would be great if they could be used to navigate here too.

(:

**Comment by kamiyaa** [comment]
Closed via 763815418ac3acd56aa7e936c48861ae6e73ca40

```toml
	{ keys = [ "H" ],		command = "cursor_move_page_home" },
	{ keys = [ "L" ],		command = "cursor_move_page_middle" },
	{ keys = [ "M" ],		command = "cursor_move_page_end" },
```

Feel free to re-open
