### ISSUE TITLE
Publish binaries on new release using CI

### ISSUE THREAD

**Issue by cjbassi** [kamiyaa/joshuto#17]
So there's a cool project called [trust](https://github.com/japaric/trust) that you can setup in your project, so that every time you create a new release/create a new tag, it will automatically build binaries for you using travis ci and publish them to the releases tab. This is really nice for people who want to use rust projects but don't want to have to deal with its compile times :D

edit: Looks like that project might be abandoned, but the idea is still the same. Ripgrep and Alacritty both do some sort of similar thing for their projects, so we could always check those out too.

**Comment by m040601** [comment]
Another vote for this.

This is an essential also if you're expecting people in low ressources platforms like the raspberry pi to try  it out.

It would also make it much easier to release this as a precompiled package for other distros.

Many people dont have , dont want to have, the entire rust distribution , and the constantly updating 500 mega, just to quickly try it out and compare it to other


` ... will need to research more into this when I have time. ...`

Have you also heard about github actions ?

Perhaps you can also have a look at how other cli rust tools do it, for example, skim, https://github.com/lotabout/skim/releases

**Comment by JacobTravers** [comment]
Here's the actual [diff](https://github.com/lotabout/skim/commit/1131d44731276fea7236a3c17a88c12dc9e6b827) where Github Actions was implemented for skim. I might take a shot at it if I get some time.
