### ISSUE TITLE
cannot add a mimetype for ts

### ISSUE THREAD

**Issue by Busyvar** [kamiyaa/joshuto#170]
Hello,

I tried to add this entry to mimetypes.toml : 
ts.inherit = "text_default"

But it breaks any file opening :
Unrecognized command 'quit_to_cwd'

what's wrong with it ?

regards

**Comment by kamiyaa** [comment]
I don't think the two errors are related. Regarding `quit_to_cwd`, I've decided to consolidate them into `quit`. See here: https://github.com/kamiyaa/joshuto/issues/167#issuecomment-1113962386

**Comment by Busyvar** [comment]
In 0.9.3 this message is displayed after editing mimetypes.toml:

> Error parsing keymap.toml file: missing field `default_view` at line 1 column 1
> Using default keymapping

**Comment by kamiyaa** [comment]
> In 0.9.3 this message is displayed after editing mimetypes.toml:
> 
> > Error parsing keymap.toml file: missing field `default_view` at line 1 column 1
> > Using default keymapping

There were changes to `keymap.toml` that now allows users to map keys depending on the `mode` or `view` the user is in.

So simply add

```toml
[default_view]
```
to the top of `keymap.toml` and it should be good.

Or take a look at https://github.com/kamiyaa/joshuto/blob/main/config/keymap.toml#L1

Hope this helps!

**Comment by Busyvar** [comment]
Keymap configuration has been merged correctly now, thanks!
