### ISSUE TITLE
use xdg-open for default application instead of configuration file

### ISSUE THREAD

**Issue by mathiasbolle** [kamiyaa/joshuto#178]
This is just a suggestion but it would be way easier to configure the default application with xdg-utils instead of configure it on 2 places (xdg-utils and the .toml file)

**Comment by krivahtoo** [comment]
There is an option in `joshuto.toml` to use xdg-open if joshuto does not know how to open a file
https://github.com/kamiyaa/joshuto/blob/f22eecdd3b7addb9b20ec4510106c6ee339d215e/config/joshuto.toml#L1
