### ISSUE TITLE
Deletions in mounted folders

### ISSUE THREAD

**Issue by maximyurevich** [kamiyaa/joshuto#184]
Hello, I see your file manager support Async I/O. All great, I think your file manager less laggy than lf, but I have deletion lags with mounted dropbox (dbxfs) folder

**Comment by maximyurevich** [comment]
This will be good

**Comment by kamiyaa** [comment]
Re-opening to track progress

**Comment by kamiyaa** [comment]
Closed via 743354da056c65c6ce0910394230270ef793d8cc
