### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by alvaro17f** [kamiyaa/joshuto#190]
Greetings!
As far as I love this app, I cannot find a way to create a symlink from a selected/copied item.
For example: in lf you can yank an item and paste it as a symlink wherever you want due to the :link command.
Would it be possible to replicate this behaviour in joshuto?
Thanks in advance.

**Comment by kamiyaa** [comment]
Yeah, we can add this feature :+1:

Currently there is a `cut_files` and `copy_files` command.
Which is "yanking" the files and storing it with a specific action to take once `paste_files` command is execute.
We can implement `link_files` where it behaves like cut and copy, adding a new action for paste to execute on.

What do you think?

**Comment by alvaro17f** [comment]
That would be really awesome.
I'd like to help and contrib, but I'm fairly new with rust, so maybe in the future.
You're doing a great job with joshuto BTW.

**Comment by kamiyaa** [comment]
Closed via 7ee7a761ec62a065fcc2bde9d98b587d069b364a

If you could suggest what the default keybinding for this command should be, that would be awesome :+1:

**Comment by DLFW** [comment]
The ranger keybinding would be
* `pl` for symlinking absolute path
* `pL` for symlinking relative path

I think they make sense.

Feature very much appreciated! :smiley:

**Comment by alvaro17f** [comment]
Thanks @kamiyaa that was really fast!
I agree with @DLFW, that sounds very good.

**Comment by kamiyaa** [comment]
Currently there is only symlink via absolute path

**Comment by kamiyaa** [comment]
Closed via https://github.com/kamiyaa/joshuto/commit/e7755ad0be98540c777d86c67605386ff11522a3
