### ISSUE TITLE
Some commands are unrecognized in version 0.9.4

### ISSUE THREAD

**Issue by CharlesChiuGit** [kamiyaa/joshuto#201]
As title, there're few commands not working. When I enter joshuto and leave, some error pups up.

```txt
❯ joshuto 
Unrecognized command 'escape'
Unrecognized command 'numbered_command'
Unrecognized command 'numbered_command'
Unrecognized command 'numbered_command'
Unrecognized command 'numbered_command'
Unrecognized command 'numbered_command'
Unrecognized command 'numbered_command'
Unrecognized command 'numbered_command'
Unrecognized command 'numbered_command'
Unrecognized command 'numbered_command'
Unrecognized command 'symlink_files'
Unrecognized command 'symlink_files'
Unrecognized command 'toggle_visual'
```

I'm using the 0.9.4 binary released file, with the configs mostly copied from main branch. Is the problem being the binary is out of date? If so, is there going to have a new release soon?

Thanks for the great work!

**Comment by kamiyaa** [comment]
> Is the problem being the binary is out of date?

Correct. I recommend building joshuto from source to stay up to date.

> If so, is there going to have a new release soon?

Good question haha. I will probably get around to releasing a new version soon :tm:

> Thanks for the great work!

Thank you!

**Comment by CharlesChiuGit** [comment]
thanks for the quick reply!

ok, I'll try to build from source, but I always had a hard time using cargo lol.
Will try again!

Thanks again!
