### ISSUE TITLE
Feature request: add command to edit file with `$EDITOR`

### ISSUE THREAD

**Issue by fritzrehde** [kamiyaa/joshuto#212]
I am still using `lf`, but want to completely switch to `joshuto`. One feature of lf that I miss here is an `edit` command to open a file in `$EDITOR` instead of opening according to the mimetype. A use case I can imagine would be executing executable shell scripts or binaries with the normal `open` command, but still being able to edit them with your `$EDITOR`.

**Comment by DLFW** [comment]
Hi,
not sure if I'm gonna tell you something you already know, but you can use `spawn` and `shell` to fire up other “editors”. You just can't use environment variables for the commands (afaik).

For example, I use some bindings like these:
```toml
keymap = [
        // ...
	{ keys = [ "t", "a" ],  command = "spawn addtag %s" },
	{ keys = [ "t", "r" ],  command = "spawn rmtag %s" },
	{ keys = [ "i" ],       command = "spawn sxiv -t %s" },
	{ keys = [ "e", "v" ],  command = "shell nvim %s" },
]
```
So `ev` always opens a file in neovim, while `i` will always open a file or dir in sxiv.

Is the use of environment variables crucial for you?

**Comment by fritzrehde** [comment]
Thanks, this solution is fine. However, I found no mention of `%s` being replaced by the current file in the documentation keymap.toml, this should definitely be added. `$EDITOR` doesn't work, I assume it's because the `shell` command isn't executed in a subshell but directly.

**Comment by fritzrehde** [comment]
I should probably leave this open until the documentation of `shell` has been updated to mention `%s`.

**Comment by DLFW** [comment]
Here we go: #217
