### ISSUE TITLE
rename command: use find instead of rfind

### ISSUE THREAD

**Issue by fritzrehde** [kamiyaa/joshuto#224]
When using the rename commands `rename_append` and `rename_keep_ext`, the last `.` is used as the seperator between the prefix (the name) and the suffix (the extension). Is there a reason for this? I just ran into the example of a tar file with the extension `.tar.gz`. The current implementation would select the second dot as the seperator between prefix and suffix, but usually I just want to change the name and leave the `.tar` there, but `rename_keep_ext` would delete everything except `.gz`. I think replacing `rfind` with `find` in `rename_file.rs` would make sense (I could quickly create a pull request). I think both `rename_append` and `rename_keep_ext` should be changed.

**Comment by DLFW** [comment]
Hi!
I’m actually not so sure if that’s a good idea. `tar.gz` is a bit of an exception. I think there are much more examples in (my) real life where I have a dot as part of the name than having it as part of the suffix. Just my two cents. :)

**Comment by fritzrehde** [comment]
What are those examples? I feel like a dot shouldn't really be part of a name (I'd use an `_` for seperating logic), but that's just my opinion.

**Comment by kamiyaa** [comment]
Imo it makes more sense to do rfind. In most cases its correct.

And for `.tar.gz`, I believe its technically archived first (`.tar`), then a compressed is applied (`.gz`, `.bz2`, `.xz`, etc.).
So its makes sense to start place the cursor before the `.gz` as thats what the file type is; a compressed singular file.

**Comment by fritzrehde** [comment]
Ok, I see your point.
