### ISSUE TITLE
add bookmarks

### ISSUE THREAD

**Issue by pantosaur** [kamiyaa/joshuto#225]
I know this was the purpose of issue #58 , but I would like to ask if it can be reconsidered. Bookmarking something while browsing directories is very different from editing the keybinding configs and much more dynamic, and is something I use all the time. For example, the directory/workspace/project you are working in can be subject to frequent change, and I think being able to mark the dir through a UI command in 2 key presses is a must against opening a tab, navigating to .config/joshuto, opening the editor, adding a line, closing editor, closing tab.

**Comment by rousbound** [comment]
I endorse this issue, this is the most important feature for me that is missing and keeping me from switching from ranger to joshuto.

**Comment by kamiyaa** [comment]
Yeah, I think this is a valid point.
I can look into implementing it.

Just off the top of my head, I'm thinking:

1. new commands
 - `add_bookmark`: add or update existing bookmark keybinding
 - `cd_bookmark` : shows menu to navigate to bookmark
 - `save_bookmarks`: maybe necessary? If we don't want it to always automatically save

2. potentially a new option?
I see ranger has the `autosave_bookmarks` option. Not sure if this is useful to anyone.

3. Bookmark file format
To keep with the current config format, I would probably use a `bookmarks.toml` file. But I'm open to other formats if it does require manually coding the parsing.

**Comment by pantosaur** [comment]
personally, I don't think save_bookmarks for a case where you want to create bookmarks that you want to use only for the current process would have much of a use but maybe im wrong.  autosave_bookmarks in ranger is for saving immediately when creating a new bookmark vs. when ranger exits. The former makes more sense to me as a default. the option is ok but not entirely necessary. toml makes sense, since it already integrates with the rest of the program, and is popular in rust, and also easy to understand.

**Comment by kamiyaa** [comment]
Added in 5d4cc2dd61b91db28aa127347450a05cb0f2d45d

**Comment by rousbound** [comment]
Awesome! I Just tried here the new feature and it's working well so far.

There are still some details in general that I need to get right before doing the migration, but this was a huge step into me ditching ranger for good.

 Nice work!

**Comment by thepenguinthatwants** [comment]
Adding bookmark by keybinding on the fly and going back later would be nice and snappy. 
Having ability to  open up a bookmark from the earlier set list is already quite good.
GJ!!
