### ISSUE TITLE
Hexadecimal representation of tabs 

### ISSUE THREAD

**Issue by rousbound** [kamiyaa/joshuto#233]
![joshuto](https://user-images.githubusercontent.com/40251117/205461751-20c38cdc-48fe-4718-a801-c9b9a507a891.png)

When I try to build joshuto it always comes with this hexadecimal numbers instead of the tabs numbers on the right upper corner.

I've tried to build with "--release" and "--all-features" flags, but it always comes like this.

It's not a problem of the terminal, because with the pre-built joshuto that doesn't happen.

Does anyone have any ideas how to solve this?

Thanks in advance.

**Comment by kamiyaa** [comment]
This is a new "feature" I guess.
Instead of tabs being stored in a vector, its being stored in a hashmap with ids.

I can however, add the numbers back if you would like

**Comment by DLFW** [comment]
Ranger shows a tab-index and then the dir name. IMHO, that's the best option for the user to keep track what is opened where and how to activate each tab.
![Screenshot_ranger_tab_dir](https://user-images.githubusercontent.com/22507197/205516369-e9e7a842-6f33-495e-8f65-a0d4b247c738.png)

Would be great if we can have that for Joshuto. ;)

**Comment by rousbound** [comment]
> This is a new "feature" I guess. Instead of tabs being stored in a vector, its being stored in a hashmap with ids.
> 
> I can however, add the numbers back if you would like

Well, I did not expect that xD. I personally found it a little bit distracting.

One option is the old one, which shows the tab as an Id out of the total tabs. 

Ex: "1/3"

The other one is range'rs with the example of the comment above.

Ex: "1: joshuto", "2: src"

The ranger's one is good because it identifies the directory the tab it is in, but in the other hand it becomes a like bit cluttered if your terminal window is short and you have lots of tabs.

Another option that we might consider is a 'carroussel-like' display:

Ex: |"9: /root", "1:joshuto", "2: src" |..... "3: /etc/passwd", "4:/var/log/apache2"....

Where only three are shown at a time, and the middle one is the current, so you would see PREVIOUS, CURRENT and NEXT tabs at a time. 

But these are just ideas, I don't use this feature very much actually, I mostly use bookmarks to jump around instead.

If it didn't show anything on the upper corner when you have just one tab it would be enough for me I think.

**Comment by DLFW** [comment]
This carousel-thing sounds really good to me. :+1: I just thought that if would have something like that, we could actually get rid of the path of the current directory in the “title bar” and instead show the current tab with its full path. Let's say I'm currently in tab 2 out of 3 and in directory `/foo/bar/tab2dir`, the first line could show something like
```
user@machine  |tab1dir|/foo/bar/baz/tab2dir|tab3dir|
```
Of course with the active tab (in the middle) highlighted.

Maybe we could even move the `user@machine`-part into the footer or make it optional via config. With the carousel-behavior,  we would have a very efficient tab-bar on the top.

Opinions?

**Comment by kamiyaa** [comment]
Yeah, both solutions look good.

```
user@machine  |tab1dir|/foo/bar/baz/tab2dir|tab3dir|
```
This is particularly interesting. I will probably take a crack at this and see if I like it xd

**Comment by kamiyaa** [comment]
I've added back the directory name as the preview.

The solution proposed by @DLFW imo is a bit more complicated to implement so I've put off on it for now.

**Comment by DLFW** [comment]
> I've added back the directory name as the preview.
@kamiyaa: I just see the first four letters of the current dir. Is that intentional?

**Comment by kamiyaa** [comment]
> > I've added back the directory name as the preview.
> 
> @kamiyaa: I just see the first four letters of the current dir. Is that intentional?

Yes, mostly to reduce space taken

**Comment by DLFW** [comment]
Just wanted to mention that I have taken up work on a “carousel” solution for the tab-bar as proposed by @rousbound.

**Comment by DLFW** [comment]
Took way longer than expected... But finally the PR is out. Hope you guys like it.
