### ISSUE TITLE
Picture preview doesnt work

### ISSUE THREAD

**Issue by og900aero** [kamiyaa/joshuto#236]
I have a working Ueberzug (ranger, vifm, lf works with it). I installed joshuto, copied the config files under .config/joshuto. I have created a joshutorun file and its content is the joshuto wrapper script. After that, I created the required 2 files under .config/joshuto: on_preview_shown and on_preview_removed. All three are runnable. Then I pasted it into the joshuto.tml file:
```
[preview]
preview_shown_hook_script = "~/.config/joshuto/on_preview_shown"
preview_removed_hook_script = "~/.config/joshuto/on_preview_removed"
```

But the preview images are not displayed. The complete window itself is not displayed. The strange thing is that there is a line in joshuto.tml that says:
preview_script = "~/.config/joshuto/preview_file.sh"

Does this require use_preview_script = true ? If so, then in this file under the image there is kitty, not ueberzug.
So I don't understand how it would be able to work then.

**Comment by DLFW** [comment]
Hi!
Some questions to start with:
* What version of Joshuto do you use? Latest from repo? I don't see any `use_preview_script` in `joshuto.toml`. Maybe you use an old version? There is some mentioning of `use_preview_script`  in the `preview_file.sh`, but that's a residual from ranger. Would be great if somebody (maybe me) would find some time to clean this template up.
* What do you mean with “The complete window itself is not displayed”? Do you mean Joshuto doesn't show up? What's the window here?
* “If so, then in this file under the image there is kitty, not ueberzug.”: I have no clue what you're talking about. What file? What image?
* You can check my working joshuto config with Überzug here: https://gitlab.com/DLF/dotfiles/-/tree/master/dotfiles/.config/joshuto
  Be aware that I currently use a version which uses thumbnails instead of the real image, but you will see that the repo contains a `on_preview_shown` and a `on_preview_shown_thumb` script. Both work, just use the non-thumb version.

**Comment by og900aero** [comment]
I use 0.9.4 version. Use Debian 11.5, and downloaded fresh Rust (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh), then ran cargo install --path=. --force --root=/usr/local. I see preview_file.sh file in .config/joshuto. Begin this rows:
```
#!/usr/bin/env bash

set -o noclobber -o noglob -o nounset -o pipefail
IFS=$'\n'

## If the option `use_preview_script` is set to `true`,
## then this script will be called and its output will be displayed in ranger.
## ANSI color codes are supported.
## STDIN is disabled, so interactive scripts won't work properly

## This script is considered a configuration file and must be updated manually.
## It will be left untouched if you upgrade ranger.
```
And also contains following rows:
```
handle_image() {
	## Size of the preview if there are multiple options or it has to be
	## rendered from vector graphics. If the conversion program allows
	## specifying only one dimension while keeping the aspect ratio, the width
	## will be used.
	local DEFAULT_SIZE="40x30"

	local mimetype="${1}"
	case "${mimetype}" in
		## Image
		image/*)
			kitty +kitten icat \
				--transfer-mode file \
				--place "${PREVIEW_WIDTH}x${PREVIEW_HEIGHT}@${PREVIEW_X_COORD}x${PREVIEW_Y_COORD}" \
				"${FILE_PATH}"
			exit 7
			;;
	esac
}
```
_What do you mean with “The complete window itself is not displayed”? Do you mean Joshuto doesn't show up? What's the window here?_

I use column_ratio = [4, 4], and the last preview window not shown, when navigate to pictures.

**Comment by og900aero** [comment]
When I quit joshuto wrapper, I get error message too:

```
$ joshutorun
ueberzug started
Failed to parse app config: No config directory found
```

**Comment by og900aero** [comment]
Yo
ur on_preview_shown file is doesnt work on my configuration. Show error message. And if I compare it with the example in the documentation, it is completely different:

Your config: 
```
case "$mimetype" in
    image/png | image/jpeg)
        meta_file="$(get_preview_meta_file $path)"
        y_offset=`cat "$meta_file" | grep "y-offset" | awk '{print $2}'`
        y=$(( $y + $y_offset ))
        show_image "$path" $x $y $width $height
        #show_image `allmytoes -sx "$path"` $x $y $width $height
        ;;
    *)
        remove_image

esac
```
Documentation config:
case "$mimetype" in
    image/png | image/jpeg)
        show_image "$path" $x $y $width $height
        ;;
    *)
        remove_image

esac

**Comment by og900aero** [comment]
So, the solution is, use original on_preview_shown file from https://github.com/kamiyaa/joshuto/tree/main/config, and use yout preview.sh, because the preview_file.sh from https://github.com/kamiyaa/joshuto/blob/main/config/ doesnt work.

But I have a new problem. Doesnt show preview gif files. I edited your file from image/png | image/jpeg) to image/png | image/jpeg | image/gif), but doesnt show previewed gif files, only the jpg and png.

**Comment by DLFW** [comment]
I did a [quick try for my dots](https://gitlab.com/DLF/dotfiles/-/commit/1b3e10ff62bce2c7f41dd327343bd20dcc0eaf84) and showing GIFs works fine for me. The image-preview scripts in the joshuto docs are just examples, you need to adapt then for your needs. As you don't show us your config, we can just guess what you have scripted on your machine. In my case, I handle the images in both, the preview-show hook-script and `preview.sh`. The first is mandatory if you want to add GIFs, the latter I use to also show some additional infos as text in the preview-pane of joshuto. That is also described [in the docs](https://github.com/kamiyaa/joshuto/blob/main/docs/image_previews.md#combining-text-preview-and-thumbnails).
