### ISSUE TITLE
# Issues on **keyboard configuration**

### ISSUE THREAD

**Issue by fatualux** [kamiyaa/joshuto#244]
##### I read the documentation about config options, so I found that:
Joshuto reads configurations from the following directories using environment variables (in order of precedence):
 - `$JOSHUTO_CONFIG_HOME`
 - `$XDG_CONFIG_HOME/joshuto`
 - `$HOME/.config/joshuto`

**Comment by DLFW** [comment]
Joshuto does not create a config directory or the config files. If no config files are provided, Joshuto uses a (compiled in) default config. To create your own configuration, create the config dir and the config files for which you want to override the defaults.

The joshuto repo has “templates” for these in the [`config` dir](https://github.com/kamiyaa/joshuto/tree/main/config). You can copy those and start modifying them.

So, you need to create `/home/yourname/.config/joshuto` and place the config files there. `$XDG_CONFIG_HOME` - if present at all - usually points to `/home/yourname/.config`. Other values are for special cases. So is `$JOSHUTO_CONFIG_HOME`; it's helpful for development or if you want to use different configs for joshuto in different scenarios/use cases. It's not necessary in a basic setup.

BTW, that's the common way how lightweight tools handle their configs. If you're not happy with the defaults, you have to create the config files yourself. Even vim works like this. Joshuto is no exception here.

Hope that helped. ;)

**Comment by fatualux** [comment]
Thanks a lot for your answer.
Before reding this, I have managed to customize my settings by editing joshuto.toml and keymap.toml before the installation (through cargo).
I want to try the method you suggest, otherwise I have to cargo uninstall and rebuild the bin everytime I change the config.

**Comment by DLFW** [comment]
Neh... Believe me, you don't have to rebuild just for changing the configuration :smiley: Have done it a hundret times. Your personal configuration has nothing to do with the build and you can just edit the tomls in your `/home/foobar/.config/joshuto` dir anytime. Changes are then used for any newly started joshuto instance.

**Comment by fatualux** [comment]
Thanks a lot for your support :)
In my opinion this is an awesome project, today I have uninstalled Ranger and replaced it with joshuto.
I just miss the previews of text and media, I can not make the script working.
I shall read the documentation again.

**Comment by OnePieceJoker** [comment]
I created the config directory and set JOSHUTO_CONFIG_HOME, but the [quit --out-put-current-directory] configuration did not take effect.

Sorry, I don't know how to solve this problem

![2023-07-25_11-24](https://github.com/kamiyaa/joshuto/assets/25676220/e5bcec09-967b-402c-bb30-df51b142794c)

keymap.toml:
![2023-07-25_11-27](https://github.com/kamiyaa/joshuto/assets/25676220/1036eb41-6a16-4885-b5cb-21f1b8703aed)


joshuto key map:

![2023-07-25_11-28](https://github.com/kamiyaa/joshuto/assets/25676220/4e46073f-5abf-412c-ac6a-864e77d45ee9)
