### ISSUE TITLE
All keycodes are unrecognized

### ISSUE THREAD

**Issue by nifker** [kamiyaa/joshuto#25]
I tried version 0.7.1 and upstream git.
Every key I try to use is an "Unknown keycode".
Tried with alacritty, mate-terminal, xterm.

**Comment by nifker** [comment]
Config files were placed wrongly.

**Comment by kamiyaa** [comment]
On that note, the dev branch has changed the way keycodes are mapped, so that modifier keys can be mapped (Ctrl, Alt, Shift, etc.)
See https://github.com/kamiyaa/joshuto/blob/dev/config/keymap.toml

**Comment by nifker** [comment]
Ive seen that - but I also had the issue that I cant use backspace when renaming files it creates a 'ć' instead.

**Comment by kamiyaa** [comment]
Yes, that is a problem I've noticed when using joshuto on other setups. There will probably be a configuration for certain keys because keyboards have different keycodes for some keys.

**Comment by kamiyaa** [comment]
@nifker see [keymap.rs struct](https://github.com/kamiyaa/joshuto/blob/dev/src/config/keymap.rs#L69) (added in dev 3cba2ba36e826985c160e58faf556a6b2d17fbcb) and [keymap.toml example](https://github.com/kamiyaa/joshuto/blob/dev/config/keymap.toml)

**Comment by nifker** [comment]
@Kamiyaa ok that works now but I think it will be better for most users if it works out-of-the-box for both configurations.

**Comment by kamiyaa** [comment]
@nifker out-of-the-box for both configurations?

**Comment by nifker** [comment]
@kamiyaa so that backspace works whether even when they dont change their config, on different system which where the code for BS slightly differs.

**Comment by kamiyaa** [comment]
@nifker bfb110a7c6a23692d6ffeca616aa5ca070869797 should allow backspace to work on 99% of cases. Thanks for the feedback :+1:

**Comment by nifker** [comment]
@kamiyaa thats working too. Very neat file manager :D
Ill post some other improvement soon too. Ill try to get into the code base and see if I can do some improvements too.

**Comment by kamiyaa** [comment]
@nifker awesome! :D 
The code base is quite messy right now and questionable designs :sweat_smile: 
Feel free to make big changes to it :+1:
