### ISSUE TITLE
[Feature] Exit with cd into the current dir

### ISSUE THREAD

**Issue by ztlevi** [kamiyaa/joshuto#26]
Hi, thanks for the awesome project.

I notice that joshuto doesn't exit with cd into the current browsed dir. Is it possible to match this behavior?

**Comment by kamiyaa** [comment]
Will probably need to write some sort of hack for this. I will see what I can do

**Comment by PolyMeilex** [comment]
As far as I know, this would require some really hanky code or a shell plugin. It would be probably better to start nested shell instance inside of `joshuto` like `ranger` does with it's `S` shortcut

**Comment by ztlevi** [comment]
It looks like ranger is using some ipc magic. 

See the [signal lib](https://github.com/ranger/ranger/blob/master/ranger/core/tab.py#L169) and [signal_emit](https://github.com/ranger/ranger/blob/master/ranger/core/tab.py#L169)

**Comment by ztlevi** [comment]
@kamiyaa I found the way to change dir on exit. This is the script I use. Take a look at ranger's `--choosedir` option. It dumps last visited dir path to that file and then will be used for `cd`. You can provide similar options.
```
ranger-cd () {
        tmpfile='/tmp/choosedir'
        curdir=$(pwd)
        ranger --choosedir="$tmpfile" "${@:-$curdir}"
        if [[ -f "$tmpfile" ]] && [[ $(cat "$tmpfile") != $curdir ]]
        then
                cd $(cat $tmpfile)
        fi
        rm -i -f "$tmpfile"
}
```

**Comment by ztlevi** [comment]
@kamiyaa Hi, did you happen to realize this approach? I would like to contribute but my rust language is poor...

**Comment by kamiyaa** [comment]
added via a600e132ddf1a0421eb2f0893366cc17a31200a5

Usage:
```sh
#!/bin/bash

OUTPUT_FILE=/tmp/$USER/joshuto-lastdir
joshuto
LASTDIR=$(cat $OUTPUT_FILE)
cd "$LASTDIR"
```
alternatively using an alias:
```sh
alias joshuto='joshuto --lastdir /tmp/$USER/joshuto-lastdir; LASTDIR="$(cat /tmp/$USER/joshuto-lastdir)"; cd "$LASTDIR"'
```

Feel free to re-open if there are still issues

**Comment by ztlevi** [comment]
@liamtimms you can checkout my setup https://github.com/ztlevi/dotty-config/blob/main/shell/joshuto/rc.zsh. But agree, this part need clearer documentation

**Comment by liamtimms** [comment]
Thanks, it seems I had to switch to the git version to get that to work, but I did adapt it to work now. It definitely would benefit from more information in `--help` or the addition of a man page.

**Comment by kamiyaa** [comment]
Hey, everything should be documented under `docs/`

For example, https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md#general
explains the new behavior of the `quit` command.

If you feel this is not enough documentation, feel free to add to it.
I'm also open to the idea of a manpage or making `--help` more useful. :+1:
