### ISSUE TITLE
Feature request: An undo button

### ISSUE THREAD

**Issue by rasmus-kirk** [kamiyaa/joshuto#268]
An undo button would be nice. Something that would take you to the previous directory, it could also undo the closing of tabs.

**Comment by DLFW** [comment]
> Something that would take you to the previous directory

You can bind something to `cd -`, which takes you to the last dir.
For example:
```
{ keys = [ "g", "b" ],		command = "cd -" },
```
Using that key-chord multiple times will toggle between two dirs, if that's what you want. It won't go back more steps in history.

My opinion about the feature request: A _button_ is not really an option for Joshuto's UI, but the function as such sounds really useful, specially the “reopen tab” thing. A general “undo” command might not be possible/feasible, but a specific command to go back in directory-history and another specific command to re-open closed tabs should be doable.

**Comment by kamiyaa** [comment]
An undo button would be a bit tricky to implement. Probably need to modify the main event loop, create undo actions for each command, etc.
