### ISSUE TITLE
Error messages printed each time joshuto is used.

### ISSUE THREAD

**Issue by D0bhareach** [kamiyaa/joshuto#272]
v 0.9.4
Error msg:
arg: "--foreground=true"
Keymap error: delete_files: unknown option '--foreground=true'

Please, have a look in impl_from_str.rs:251 - eprintln unconditionally print.
And in joshuto/config/keymap.toml:(75&76) - arg = "--foreground=true" shall be
"--background=true"

**Comment by kamiyaa** [comment]
Should be fixed in 6e968f8
