### ISSUE TITLE
Ubuntu Terminal keymapping for Alt+[number]

### ISSUE THREAD

**Issue by D0bhareach** [kamiyaa/joshuto#273]
Help buffer show this mapping for switching between terminals:
Alt+1        tab_switch_index 1                                 Switch to a given tab               
Alt+2        tab_switch_index 2                                 Switch to a given tab               
Alt+3        tab_switch_index 3                                 Switch to a given tab               
Alt+4        tab_switch_index 4                                 Switch to a given tab               
Alt+5        tab_switch_index 5                                 Switch to a given tab               
In standard Ubuntu Terminal this mapping will jump between open tabs of the Terminal itself.

**Comment by kamiyaa** [comment]
You can remap these to other keystrokes of your choice 👍
