### ISSUE TITLE
Better documetation for configuration.

### ISSUE THREAD

**Issue by D0bhareach** [kamiyaa/joshuto#280]
When configuration for mimetype added it's not clear what options such as `fork` and `silent` do. `silent` set stdin and stdout to null and is complimentary to `fork`. `fork` start application in new thread.
When vim or helix is used with option `fork`. It gives bad result, because joshuto  try open vim in the same tab/window, worst it actually succeed.

**Comment by kamiyaa** [comment]
Yep, more/better documentation is always good 👍 
Will get around to it 👍

**Comment by kamiyaa** [comment]
Added more documentation in 93061c472d4d735ea48bb729216bb5a61fe92a64
