### ISSUE TITLE
No text previews

### ISSUE THREAD

**Issue by nat-418** [kamiyaa/joshuto#282]
I don't understand how to make text previews work like with `lf`, `ranger`, etc. I don't care about image previews, I just want to see the file contents in the far right pane. I've looked through the docs, issues, etc. and I am not sure if this is supposed to be automatic and something is wrong with my install or if I need to make a wrapper script or configuration change from the defaults to enable the feature.

**Comment by DLFW** [comment]
Hm, yeah, the documentation is lacking there...
Have you discovered the [example config dir](https://github.com/kamiyaa/joshuto/tree/main/config)?
It contains an example-script (`preview_file.sh`) which generates textual previews and the `joshuto.toml` there shows how to set that script as the “preview generator”.

Try to copy that preview script and add the corresponding entry into your `joshuto.toml`. (Within _your_ `~/.config/joshuto`, of course.)

Actually, this is the exact same concept as in _ranger_. In fact, the preview-script of _joshuto_ has been “forked” from _ranger_'s preview script. _Joshuto_'s preview script may still have residuals or even some dead code from that heritage. Not sure. I tried to clean it up some time ago.

**Comment by nat-418** [comment]
Yes, I did look in there and copy the file and search the issues etc. The issue is that it doesn't work.

**Comment by kamiyaa** [comment]
Hey, thanks for the issue.
I'll make a writeup/documentation on the preview aspect of joshuto :+1:

**Comment by nat-418** [comment]
Here's what I did:

1. I copied the example joshuto.toml to ~/.config/joshuto/joshuto.toml
2. I copied the example preview_file.sh to ~/.config/joshuto/preview_file.sh, marked it executable, and put it on my $PATH.
3. I did the same for the example wrapper script.

**Comment by DLFW** [comment]
> 4\. I added `use_preview_script = true` to the bottom of my ~/.config/joshuto/joshuto.toml file.

Where is that coming from?
You need some
```
[preview]
...
preview_script = "~/.config/joshuto/preview.sh"
...
```


> 3\. I did the same for the example wrapper script.

Not sure what you mean. The example wrapper for the image-previews? If so: that's not necessary for the text preview (but it doesn't hurt either).

**Comment by nat-418** [comment]
> Where is that coming from?

From reading `preview_file.sh`:

```
#!/usr/bin/env bash

set -o noclobber -o noglob -o nounset -o pipefail
IFS=$'\n'

## If the option `use_preview_script` is set to `true`,
## then this script will be called and its output will be displayed in ranger.
## ANSI color codes are supported.
## STDIN is disabled, so interactive scripts won't work properly
```
