### ISSUE TITLE
move from tui to ratatui

### ISSUE THREAD

**Issue by Ragnyll** [kamiyaa/joshuto#289]
it looks like tui, a core dependency to this project is unmaintained. see https://github.com/fdehau/tui-rs/issues/654
The maintainer and community behind the project has moved to https://github.com/tui-rs-revival/ratatui .

I think that it's in the interest of this project to move the dependency to ratatui.

**Comment by Ragnyll** [comment]
I'll start looking into making this switch if you want to assign this issue to me. I imagine that i'll probably just find the version with parity to the current dependency, then look at bumping it after that. It sounds like the new maintainers are looking to do some major changes in the coming future.

**Comment by kamiyaa** [comment]
Interesting! I wasn't aware of this and I'll definitely look into helping the tui community.

Yep, I can assign this to you. Thank you! ♥️

**Comment by Ragnyll** [comment]
Opened the pr https://github.com/kamiyaa/joshuto/pull/290

**Comment by kamiyaa** [comment]
Closed via #290
