### ISSUE TITLE
You don't know about generic variables

### ISSUE THREAD

**Issue by og900aero** [kamiyaa/joshuto#293]
I want to edit mimetype.toml to the following:

{ command = "imv-x11", args = [ "-n", "--", "$PWD" ], fork = true, silent = true },

This is necessary because if I enter the path ($PWD) of the given image, then in the case of the opened image, you can navigate to the other images in that directory with the right and left buttons. I try $path, but doesnt work too.

**Comment by Sonico98** [comment]
Using simply a dot (".") works.
```{ command = "imv", args = [ "-n", "--", "." ], confirm_exit = true }```

However, imv is not translating "--" to a filename, instead it outputs `Invalid starting image: --`. So, imv browses the directory just fine, but the starting image is always the first in the folder.

**Comment by og900aero** [comment]
> Using simply a dot (".") works. `{ command = "imv", args = [ "-n", "--", "." ], confirm_exit = true }`
> 
> However, imv is not translating "--" to a filename, instead it outputs `Invalid starting image: --`. So, imv browses the directory just fine, but the starting image is always the first in the folder.

It is problem, because this solved under ranger and lf :(

ranger : mime ^image, has imv-x11, X = imv-x11 -n "$@" "$PWD"
lf : imv-x11 -n "$fx" "$PWD"
