### ISSUE TITLE
Please consider publishing a Homebrew package

### ISSUE THREAD

**Issue by theniceboy** [kamiyaa/joshuto#294]
Homebrew seems to be the more popular macOS package manager. Please consider publishing a package to Homebrew.

**Comment by kamiyaa** [comment]
Always open to the idea of adding Joshuto to more package managers, but I'm probably unfit for the job to maintain them.
If anyone wants to maintain a homebrew package of Joshuto, feel free!

**Comment by kukat** [comment]
for now, you can use my tap to install joshuto

```
brew install kukat/joshuto/joshuto
```

@kamiyaa i'm happy to transfer this homebrew tap repo to your github namespace.

**Comment by noahlias** [comment]
The official [package](https://github.com/Homebrew/homebrew-core/pull/132448) has released. 😆 

<img width="620" alt="image" src="https://github.com/kamiyaa/joshuto/assets/3949397/54c16a20-6ec8-4927-a918-a1290c18056b">

**Comment by DLFW** [comment]
Not an Apple guy, but congrats! :smile:  :+1: 

BTW, just realized that Joshuto is **L**GPL... :thinking:

**Comment by Beethoven-n** [comment]
if the official package is released, we should probably close this

**Comment by Summer-Field** [comment]
> for now, you can use my tap to install joshuto
> 
> ```
> brew install kukat/joshuto/joshuto
> ```
> 
> @kamiyaa i'm happy to transfer this [homebrew tap repo](https://github.com/kukat/homebrew-joshuto) to your github namespace.

That helps me a lot, thanks!
