### ISSUE TITLE
Implementation of Devicons?

### ISSUE THREAD

**Issue by gottaStartNow** [kamiyaa/joshuto#3]
I am a long time user of Ranger and I love it but I always have to install devicons to make it more readable, https://github.com/alexanderjeurissen/ranger_devicons, can this be built into joshuto?

**Comment by kamiyaa** [comment]
I will probably get around to this. Currently busy with school.
Feature-wise, right now I'm more focused on getting things to work with wide characters and readline like input support.

**Comment by gottaStartNow** [comment]
Thank you for the update. I look forward to it.

**Comment by gottaStartNow** [comment]
So it won't automatically populate the icon type next to the end of the file name? There are dozens of characters and probably many more. I am trying to figure out how I would implement the devicons in the file.

**Comment by kamiyaa** [comment]
I can probably provide a script later or something. The configuration for this I am still unsure of, so it might change in the future

**Comment by gottaStartNow** [comment]
Scripting is good. Think about the configuration for a while then, ain't in no rush or nothing.

**Comment by gottaStartNow** [comment]
Did you get around to this yet?

**Comment by kamiyaa** [comment]
Sorry, I've been busy recently

**Comment by gottaStartNow** [comment]
It is fine. Just love the project man.

**Comment by kamiyaa** [comment]
Closing via #31
