### ISSUE TITLE
Missing Cargo.lock

### ISSUE THREAD

**Issue by foxfriends** [kamiyaa/joshuto#30]
~~When I checkout master and run `cargo build`, there are all sorts of build errors to do with the `tui` crate.~~ Never mind that, I just had some old checkout lying around with the wrong versions.

That said, there is still no `Cargo.lock` file, which should generally be committed for binary projects so that the correct dependency versions are always downloaded. See [here](https://github.com/rust-lang/cargo/issues/315)

**Comment by kamiyaa** [comment]
Fixed with 2807cbd6b8a7a5d7e4766e11d7671b8bbf98f290
