### ISSUE TITLE
Fonts not rendered

### ISSUE THREAD

**Issue by geometrylearner** [kamiyaa/joshuto#301]
I have compiled the joshuto in my gentoo GNU/Linux system where most of the unicode fonts invoked by joshuto not rendered correctly for instance '' and ' '. Can I fix this issue by `eselect fontconfig enable/disable`, or something else fonts I should install and config? Thanks.

**Comment by DLFW** [comment]
Hm, that should not be a Joshuto issue. Joshuto does not invoke any fonts. It's your terminal that has to support the respective characters. Maybe try to install a [nerd font](https://www.nerdfonts.com/) (they should have all the charsets needed and more) and check that those special chars can be displayed in your terminal.

**Comment by geometrylearner** [comment]
Thanks, you are right, move the nerdfonts directory to "/usr/share/fonts/" fixed the issue. Could close now, Thanks.

**Comment by zhlinh** [comment]
same issue on iMAC, and can not copy to /usr/share/fonts/, but the items2 display well with powerline fonts, how to solve it?
