### ISSUE TITLE
open file without extension

### ISSUE THREAD

**Issue by aklk1ng** [kamiyaa/joshuto#305]
such as `config`, `HEAD`  files, i don't know how to config it in `mimetype.toml`, i must type `nvim` everytime.

**Comment by MYRon-TO** [comment]
mimetype.toml
```
text_default	= [
    { command = "nvim" },
]
```

**Comment by aklk1ng** [comment]
@MYRon-TO , i know, but `joshuto` can't identify a file without extension like this
```toml
c.inherit = "text_default"
```
So when i try open a `config` file, the `text_default` can't work

**Comment by tarlety** [comment]
> So when i try open a `config` file, the `text_default` can't work

Which Joshuto version/commit number you use and what's your mimetype.toml?

If you are currently utilizing the latest (pre)release of Joshuto, specifically version v0.9.4, please note that this version does not support the use of mimetypes via the file command. As a result, the 'text_default' feature cannot be employed when opening a file without an extension.

You can refer to commit f117ddacc, which introduces support for mimetypes via the file command. To address the issue at hand, you can rebuild Joshuto with the latest code and ensure the proper configuration of the 'mimetype.toml' file. Once these steps are completed, you can attempt to open the file without extension again.

**Comment by aklk1ng** [comment]
@tarlety 
yes, my joshuto version is `0.9.4`, and thanks for answering!
