### ISSUE TITLE
ANSI escape codes not working in preview

### ISSUE THREAD

**Issue by rijkvp** [kamiyaa/joshuto#310]
I am using the `preview_file.sh` from this repository to display previews. However, the ANSI escape codes does not seem to work:

![image](https://github.com/kamiyaa/joshuto/assets/43184442/74731d6c-6f43-44f7-a2df-ae780f3c5c49)

I'm running the latest `0.9.4` release.

**Comment by DLFW** [comment]
Hi!
You're sure that you have a recent Joshuto version and not disabled the “syntax_highlight” feature?
Which `bat` version do you have installed?

**Comment by DLFW** [comment]
So you use the exact version 0.9.4? That is from mid of last year (quite old) and it seems that the "syntax_highlight" feature was [not enabled by default at the time](https://github.com/kamiyaa/joshuto/blob/6d230ce96e668c168a5393ef3294623986d547fc/Cargo.toml#L48).

Not a bug, just the default build-config a year back. I think that changed [Jan 2023](https://github.com/kamiyaa/joshuto/commit/80bc78d0c9a51eb7f0ca19144fe8120bc376e619) after fixing some issues with the lib that's used for interpreting the escape sequences. There were a couple of problems with it....

Try to build the latest Joshuto from the repo.

**Comment by kamiyaa** [comment]
New version released 👍 d921fc1f793467c3fe2c8f31285f3e1c51c1a328
