### ISSUE TITLE
[Feature Request] Access permission to view

### ISSUE THREAD

**Issue by gcx1024** [kamiyaa/joshuto#313]
I had installed joshuto on the server, but found that I could use it to view other users' home at will. Whether to add permission control functions to ensure security.  For example, a directory without access permission is not displayed.

**Comment by kamiyaa** [comment]
I believe this can be done at the filesystem UNIX permission level?
Ie. If we don't want other users viewing our home directory, remove executable permissions for our home directory for other users (rwxr--r--)

**Comment by gcx1024** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by gcx1024** [comment]
indeed, you're right. 😄
