### ISSUE TITLE
failed to install the latest version

### ISSUE THREAD

**Issue by namespacebilibili** [kamiyaa/joshuto#318]
<img width="914" alt="截屏2023-05-29 19 44 12" src="https://github.com/kamiyaa/joshuto/assets/91790440/b00de140-a7e3-49b4-b271-a871be42a6e0">

System: macOS Ventura

cargo version: 1.69.1, rustc version: 1.69.0

**Comment by Rongjianying** [comment]
same issue for me~~

**Comment by MathieuHerrmann** [comment]
I create a fix on this pull request : https://github.com/kamiyaa/joshuto/pull/319

**Comment by namespacebilibili** [comment]
> I create a fix on this pull request : #319

Nice of you
