### ISSUE TITLE
Cycling tabs with tab_switch -1 crashes

### ISSUE THREAD

**Issue by lahwaacz** [kamiyaa/joshuto#32]
If you have several tabs, pressing `Tab` at the last tab cycles to the first tab. But then if you want to switch to the previous tab with `Shift+Tab` on the first tab, joshuto crashes.

**Comment by kamiyaa** [comment]
Should be fixed with 9b6aea79036c40885f352d26e8a2a4892da15306.

**Comment by lahwaacz** [comment]
Thanks!
