### ISSUE TITLE
error[E0308]: mismatched types

### ISSUE THREAD

**Issue by colin4k** [kamiyaa/joshuto#321]
`   --> src/ui/widgets/tui_file_preview.rs:44:46
    |
44  |                     buf.set_spans(area.x, y, line, area.width);
    |                         ---------            ^^^^ expected `&Spans<'_>`, found `&Line<'_>`
    |                         |
    |                         arguments to this method are incorrect
    |
    = note: expected reference `&Spans<'_>`
               found reference `&ratatui::text::line::Line<'_>`
note: method defined here
   --> /home/colin/.cargo/registry/src/github.com-1ecc6299db9ec823/ratatui-0.20.1/src/buffer.rs:309:12
    |
309 |     pub fn set_spans(&mut self, x: u16, y: u16, spans: &Spans<'_>, width: u16) -> (u16, u16) {
    |            ^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.`

**Comment by alexzhang1030** [comment]
Same

**Comment by sxyazi** [comment]
Same issue, but I figure out that using `cargo build` instead of `cargo install` works:

```bash
cargo build --release
cp target/release/joshuto /usr/local/bin
```

**Comment by Eyesonjune18** [comment]
As of the latest release (0.21.0 I believe), `Spans` has been deprecated and renamed to `Line` to better reflect its usage as a type.

**Comment by alexzhang1030** [comment]
Solved by #319

**Comment by kamiyaa** [comment]
@colin4k @sxyazi Can you confirm this has been resolved in the latest git version?

**Comment by kamiyaa** [comment]
Closing for now, feel free to re-open if issue persists
