### ISSUE TITLE
Feature Request: CSI u Support

### ISSUE THREAD

**Issue by sxyazi** [kamiyaa/joshuto#323]
CSI u is an extension to the existing keyboard protocol, and is backward compatible.

The existing keyboard protocol has some known issues, such as inability to distinguish between `Tab` and `C-i`, and inability to recognize `C-1`, `C-2`, etc. for tab switching.

For more detail see:
https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by krivahtoo** [comment]
I think there will be CSI u support once migration to crossterm is done. Since crossterm already supports it.
#133

**Comment by sxyazi** [comment]
Oh I didn't know this, thanks for the info!
I will close it and focus on that one.
