### ISSUE TITLE
Include --locked install instructions

### ISSUE THREAD

**Issue by joshka** [kamiyaa/joshuto#328]
I noticed a couple of issues where the users installing this crate saw problems due to updated dependencies. Particularly the ratatui change where we renamed `Spans` -> `Line` (sorry!), but I can see there is another issue that could be similar (https://github.com/kamiyaa/joshuto/issues/315).

One suggestion that could address this (and lessen your support burden) is to ensure that users use the specific versions of the dependencies specified in your Cargo.lock file rather than updated versions by adding the `--locked` flag on the install instructions.

**Comment by kamiyaa** [comment]
Good idea! Will add it shortly
