### ISSUE TITLE
[Proposal] New release

### ISSUE THREAD

**Issue by donovanglover** [kamiyaa/joshuto#332]
The last release was [almost a year ago](https://github.com/kamiyaa/joshuto/releases/tag/v0.9.4) and [many things](https://github.com/kamiyaa/joshuto/compare/v0.9.4...1d7f9067189fbf730605f373d591654651e01689) have changed since then. Most notably, [ANSI is broken](https://github.com/kamiyaa/joshuto/issues/310) for users that use v0.9.4 of joshuto.

**Comment by realeinherjar** [comment]
Yes, +1 for this.
Please tag a new release.

**Comment by kamiyaa** [comment]
Closed via d921fc1f793467c3fe2c8f31285f3e1c51c1a328
😉 
I also agree a new release is due. I've just been busy with life 👍
