### ISSUE TITLE
Visual mode not working

### ISSUE THREAD

**Issue by fatualux** [kamiyaa/joshuto#335]
Hi,
I have mapped this shortcut

 { keys = ["V"], command = "toggle_visual" },

but toggle_visual function is not working... the status bar returns V: unmapped input

**Comment by DLFW** [comment]
Hi!
Hm, guess that is not really a "visual mode" problem, but either:
* You're keymap file you're editing is not the one Joshuto uses, or...
* You're using an old version of  Joshuto that did not yet support visual mode

Confusingly, Joshuto also gives this "unmapped input" error when the mapped command does not exist.

Please note that the last released version of Joshuto is pretty old and is from before the visual mode feature. (See #332.)
If you're using that, you might want to compile the latest from the repo until we have new version.

**Comment by DLFW** [comment]
Ah, one more thing: When you start Joshuto with a mapping to an unknown command, Joshuto will print a message. Start and then quit Joshuto and check if it printed something to the terminal, like `Keymap error: Unrecognized command 'moooo'`.

(Hope Joshuto printed that error message already in that last released version. 😄)

If you get such a message, you use an too old version that does not have that feature.

**Comment by kamiyaa** [comment]
> Confusingly, Joshuto also gives this "unmapped input" error when the mapped command does not exist.

Interesting, I will need to fix that to make it more clear 👍

**Comment by fatualux** [comment]
Thanks, now Visual mode is working.
I was using an outdated version of Joshuto, but usually I trust my AUR pkg manager to notify for updates.
The day before yesterday I updated Joshuto et voilà, everything is working :)

**Comment by fatualux** [comment]
> > Confusingly, Joshuto also gives this "unmapped input" error when the mapped command does not exist.
> 
> Interesting, I will need to fix that to make it more clear +1

thanks, Joshuto is my favourite file manager, it is awesome
