### ISSUE TITLE
Disable icons by default

### ISSUE THREAD

**Issue by imbolc** [kamiyaa/joshuto#341]
To make Joshuto look decent, one should either install the icons or replace the default config to disable them. Would you consider disabling them by default?

**Comment by Dzordzu** [comment]
> or replace the default config to disable them

So one can do it  ¯\\_(ツ)_/¯

Personally I don't see a point in disabling them by default. I started using joshuto recently and haven't found it problematic. I'm not trying to be rude, but it seems like you want the defaults to be suited for your own. Personalizing your tools is not a hard task. Furthermore I really do enjoy that Joshuto is aimed to look fancy with no configuration at all (yes, I love icons in the terminal ;) ).

**Comment by imbolc** [comment]
> haven't found it problematic

I use it as a vim file chooser which I bring to every remote server I admin. A single binary is the major benefit in this case (e.g. with ranger you have to deal with venvs etc). The necessity of bringing configs breaks it.

> I'm not trying to be rude, but it seems like you want the defaults to be suited for your own

I've tried to find a way to check if icons are installed but I couldn't. So the only way I see to make it look decent without icons is to disable them by default.

> Personalizing your tools is not a hard task.

Why do you care about sensible defaults then?

**Comment by Dzordzu** [comment]
> Why do you care about sensible defaults then?

Sensible defaults are the most convenient for the majority of users

` which I bring to every remote server I admin` and `look decent without icons is to disable them by default` are 'nice to have at once, but not obligatory'. On the servers the main purpose of the tools is to work properly. If the majority of the users have to change their configs, because single admin wants something… Well it is not sensible

 >  A single binary is the major benefit in this case 
 
 It is. It just works with single binary. If you need customization, bring in some ansible, rsync, clush, pdsh, whatever you want.  You can also recompile software yourself and suit it to your needs ;)

**Comment by kamiyaa** [comment]
I am for the idea of disabling icons by default.

1. I personally don't use them :p 
2. Most people won't have the necessary fonts out of the box so this is more of a "power user" option

**Comment by kamiyaa** [comment]
@imbolc you can also create your own custom joshuto binary by changing the default config inside the `config/` directory.
At compile time, joshuto will read the config files inside `config/` to use as the default config :+1:
This will allow you to build a joshuto with your own preset keybindings and settings

**Comment by imbolc** [comment]
> 1. I personally don't use them :p

I feel the same way. Even though I have the fonts, I ended up disabling them because they feel noisy, given that most files still have extensions.

**Comment by Dzordzu** [comment]
Personally I'm not in favor of this. Not in the near future. It will mean that many users will have to change theirs configs. I would personally do it in the 1.0.0 release. As long as it's convenient for most of the users, it's sensible NOT to brake things until major release

**Comment by imbolc** [comment]
The meaning of 0.x version is exactly the opposite :)

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
https://semver.org/

**Comment by Dzordzu** [comment]
> MAY

Doesn't mean it should

> As long as it's convenient for the most of the users, it's sensible NOT to brake things until major release

That is my major point

**Comment by kamiyaa** [comment]
Icons are disabled by default now
