### ISSUE TITLE
Unrecognized command warning on Macos

### ISSUE THREAD

**Issue by huwqchn** [kamiyaa/joshuto#346]
![image](https://github.com/kamiyaa/joshuto/assets/12139734/2a8fd118-de60-4a02-b983-f9834bd12048)

**Comment by kamiyaa** [comment]
@huwqchn are you still having this issue?

**Comment by huwqchn** [comment]
Everything is well after brew updated

**Comment by kamiyaa** [comment]
Nice! Closing this issue then
