### ISSUE TITLE
--foreground=true not working any longer

### ISSUE THREAD

**Issue by fatualux** [kamiyaa/joshuto#357]
Since I updated Joshuto (I am on joshuto-0.9.5) the --foreground=true option is no longer working (only permanently works).

This is my keymap:

 { keys = [ "delete" ],  command = "delete_files --permanently" },
 { keys = [ "d", "D" ],  command = "delete_files --foreground=true" },

**Comment by DLFW** [comment]
Hi. Removed from config template in commit 6e968f8aab4cff7f001c10c3fcbe59030dda6ed0.
I don't find the realted change in the code logic, but this option has apparently been removed. I had to remove it from my config some time ago.

**Comment by kamiyaa** [comment]
I've changed it to `--background=true` instead :eyes:

**Comment by fatualux** [comment]
thanks for your support, all clear
