### ISSUE TITLE
imgcat with joshuto image preview

### ISSUE THREAD

**Issue by noahlias** [kamiyaa/joshuto#367]
I want to preview image in **Mac iTerm**, and there is an Shell Integration Command `imgcat` to preview.

So I configured the `mimetype.toml` and `preview_file.sh`
_mimetype.toml_:

<img width="609" alt="image" src="https://github.com/kamiyaa/joshuto/assets/3949397/4e80139c-f3fc-410f-a10a-52f0a7c0768d">

_preview_file.sh_:

<img width="614" alt="image" src="https://github.com/kamiyaa/joshuto/assets/3949397/d9a10d28-3b3d-41ca-a6aa-54f49715d81b">

but it didn't work.

[![asciicast](https://asciinema.org/a/596883.svg)](https://asciinema.org/a/596883)

**Comment by DLFW** [comment]
If you want “image preview” for your files, you're digging in the completely wrong corner.... 😆

`mimetype.toml` has nothing to do with image previews and the preview-script for the text previews has only a little to do with image previews. Have your read the [docs on image thumbnails](https://github.com/kamiyaa/joshuto/blob/main/docs/image_previews/README.md)? You need to use some “hook scripts” to display images for the hovered files. 
`mimetype.toml` is only for _opening_ files. Completely different story....

**Comment by noahlias** [comment]
> If you want “image preview” for your files, you're digging in the completely wrong corner.... 😆
> 
> `mimetype.toml` has nothing to do with image previews and the preview-script for the text previews has only a little to do with image previews. Have your read the [docs on image thumbnails](https://github.com/kamiyaa/joshuto/blob/main/docs/image_previews/README.md)? You need to use some “hook scripts” to display images for the hovered files. `mimetype.toml` is only for _opening_ files. Completely different story....

😢  ,I try it about the `image thumbnails`, but it didn't work on mac iterm.

**Comment by DLFW** [comment]
> I try it with the image thumbnails, but it didn't work on mac iterm.
 
Which does not change the fact that editing `mimetype.toml` will bring you nowhere.

I recently added a description on [how to use Überzug++](https://github.com/kamiyaa/joshuto/blob/main/docs/image_previews/ueberzugpp.md) for previews. And the [projects website](https://github.com/jstkdng/ueberzugpp) tells me that it supports iterm2. So, if  I would be in your place, I would try to get Überzug++ running first. Once that's working, I would read the image-preview-docs here once more carefully and try to get it running by adapting the Überzug++ recipe for the iterm backend.

I'm not a Mac user. Guess that's all help I can give you from my side.
