### ISSUE TITLE
bulk rename not work

### ISSUE THREAD

**Issue by cap153** [kamiyaa/joshuto#368]
display environment variable not found
![image](https://github.com/kamiyaa/joshuto/assets/67049883/596206bc-b2a4-465b-9f4d-60aa675f86cb)

**Comment by DLFW** [comment]
[Variable `$EDITOR` set](https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md#bulk_rename-rename-all-selected-files)?

**Comment by cap153** [comment]
> [Variable `$EDITOR` set](https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md#bulk_rename-rename-all-selected-files)?

Yes, I set the environment variable and it worked, thank you
![image](https://github.com/kamiyaa/joshuto/assets/67049883/a1c4bba4-987f-421b-be50-bb6c96687e11)
