### ISSUE TITLE
How to configure the title length of tab?

### ISSUE THREAD

**Issue by oldflag2333333** [kamiyaa/joshuto#372]
The default length of tab is limit by 4 characters. It looks wired while using large monitor. Can I set the default length to unlimited?

**Comment by DLFW** [comment]
Hi!
That's currently hard-coded.

I'm currently experimenting with other tab-line implementations for better tab-representations, but I'm not sure how long it will take until I can provide a PR. It's not as easy as I was hoping for. 😏

Related, closed Issue: #233

**Comment by oldflag2333333** [comment]
Thanks,  hope it coming soon.👍
