### ISSUE TITLE
[Feature request] Titles for keymap commands

### ISSUE THREAD

**Issue by Beethoven-n** [kamiyaa/joshuto#373]
i'd like to have titles or comments on keymap commands, that way it's easier to tell the difference between them when you have a list of possible commands.

for example, my config adds dragon-drop support, but all the commands look exactly the same, except for the end.
```toml
keymap = [
# dragon-drop support
  { keys = [ "g","n","n" ], command = "shell dragon-drop --thumb-size 448 --and-exit --icon-only --on-top %s" },
  { keys = [ "g","n","a" ], command = "shell dragon-drop --thumb-size 448 --and-exit --icon-only --on-top %s --all" },
  { keys = [ "g","n","i" ], command = "shell dragon-drop --thumb-size 448 --and-exit --icon-only --on-top %s --target" },
  { keys = [ "g","n","t" ], command = "shell dragon-drop --thumb-size 448 --and-exit --icon-only --on-top %s --target" },
]
```

this shows up in common usage in a way that's relatively hard to read.
![image](https://github.com/kamiyaa/joshuto/assets/44652883/189dc0c1-7f47-4a01-bd30-5417e9ffbe86)
it's also kinda annoying that it's automatically alphabetically sorted, instead of being sorted in the way i entered it, but that's out of scope for this issue.

what might fix this is if the user was allowed to add a title to these commands that shows up instead of the command used.

**Comment by kamiyaa** [comment]
Yeah, thats a neat idea. I like it.
Have an optional description. If no description, resort to default.

**Comment by kamiyaa** [comment]
541f16850e33145ff657211e43a12f2327f188a6

![20230812-155208_swappy](https://github.com/kamiyaa/joshuto/assets/8345320/03087699-fe4f-49e6-8e01-f5889d47334d)
![20230812-155222_swappy](https://github.com/kamiyaa/joshuto/assets/8345320/aa2446c7-2740-42a5-bc6f-5a0fcd8e3227)

**Comment by kamiyaa** [comment]
> @kamiyaa Any chance the custom descriptions could be displayed in the help menu as well?

Did you have any use cases in mind for this?
But yes, I can add it in as well
