### ISSUE TITLE
[FR] Use system timezone for modified time instead of UTC

### ISSUE THREAD

**Issue by xfzv** [kamiyaa/joshuto#379]
```console
❯  joshuto -v
joshuto-0.9.5
```

Unless I'm mistaken, the files modified time is based on UTC. If the system timezone is not UTC, then the data isn't relevant.

It would be nice if joshuto could use the system timezone instead, like [lf](https://github.com/gokcehan/lf) or [xplr](https://github.com/sayanarijit/xplr) for instance.

**Comment by kamiyaa** [comment]
Closing because PR is merged
