### ISSUE TITLE
Feature request: line numbers

### ISSUE THREAD

**Issue by jwnpoh** [kamiyaa/joshuto#41]
Hi there, any possibility to have line numbers, absolute or relative, similar to vim? So that we can do vim movement like <#-j> <#-k> <#-gg> etc.?

Thanks for this program!

**Comment by kamiyaa** [comment]
Hey @jwnpoh , could you elaborate on what you mean by line numbers?
I'm not a big vim user so I don't know how it should look/behave

**Comment by jwnpoh** [comment]
Hi there, here's a screenshot from nvim
![screenshot from nvim](https://user-images.githubusercontent.com/56040656/112327867-c0d29d00-8cf0-11eb-924d-1a15fef22c9d.png) with absolute line numbers set. My cursor is currently on line 7. If I enter <2-g-g> my cursor will jump to line 2. Alternatively if I enter <5-k> from line 7 the cursor would move up 5 lines to line 2.

And here's a screenshot from lf ![screenshot from lf](https://user-images.githubusercontent.com/56040656/112327499-718c6c80-8cf0-11eb-9972-e1f82ef34993.png) with relative line numbers enabled. My current cursor position is on line 2, where the src folder is. The relative line numbers enable me to see immediately what number to prefix my <j> or <k> movements to quickly jump to the file I want, instead of pressing <down> or <j> multiple times to get to a file down near the bottom of the folder, for example. 

For now I'm using the built-in search function < / > to jump lines.

Does this make sense?
