### ISSUE TITLE
utils directory

### ISSUE THREAD

**Issue by kennycallado** [kamiyaa/joshuto#425]
I was updating the Dockerfile and moving it into a new **utils** directory, as I have done for the installation script. So, I was wondering if it is possible to move **nix** stuffs to keep the repo clean.

**Comment by kamiyaa** [comment]
Maybe @Ruixi-rebirth can comment on this. I'm not too familiar with the nix system. But I imagine its not possible to move it?

**Comment by Ruixi-rebirth** [comment]
> 

It is possible to move the nix directory to utils, I will make some small changes later. Until then you can do what you want

**Comment by Ruixi-rebirth** [comment]
> I was updating the Dockerfile and moving it into a new **utils** directory, as I have done for the installation script. So, I was wondering if it is possible to move **nix** stuffs to keep the repo clean.

It is possible to move the nix directory to utils, I will make some small changes later. Until then you can do what you want
