### ISSUE TITLE
File icons

### ISSUE THREAD

**Issue by luisdavim** [kamiyaa/joshuto#43]
Hi, would it be possible to add icons, something like https://github.com/ogham/exa does?

**Comment by kamiyaa** [comment]
Are you talking about these? https://github.com/alexanderjeurissen/ranger_devicons

If so, its already been implemented https://github.com/kamiyaa/joshuto/issues/3
and you enable it via:
https://github.com/kamiyaa/joshuto/blob/ec6138539b8102dd44736199ce9f3f0ecba92b40/config/joshuto.toml#L21-L22

**Comment by luisdavim** [comment]
Oh, cool, thanks.
