### ISSUE TITLE
Using the default keymap.toml Error after exit

### ISSUE THREAD

**Issue by kola-web** [kamiyaa/joshuto#432]
Failed to parse keymap.toml: TOML parse error at line 4, column 3
  |
4 |   { keys = ["escape"], commands = ["escape"] },
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
missing field `command`

**Comment by kamiyaa** [comment]
Theres been a breaking change introduced in this commit https://github.com/kamiyaa/joshuto/commit/31beaabe6b2cf4119aacae6c1722cdc1e5ba2f5b

that allows multiple commands to be ran from a single keystroke.
Looks like you're running an older version of joshuto that uses the older config.

**Comment by kola-web** [comment]
Thank you for your reply.
