### ISSUE TITLE
preview_script required for preview_shown_hook_script?

### ISSUE THREAD

**Issue by EvanCarroll** [kamiyaa/joshuto#434]
It's not at all clear to me that,

* if you don't have a `preview_script` that exists and is `+x` and returns 0, you can't get a `preview_shown_hook_script` working.
* why my `preview_removed_hook_script` doesn't work.

Now I know it, but I think the docs should reflect this very clearly.

**Comment by DLFW** [comment]
Hi!
I will add a note in the docs. [Here](https://github.com/DLFW/joshuto/tree/doc-imgprev/docs/image_previews#image-thumbnails-in-file-previews) is a proposal (the ❗-section). Do you think that gives more clarity?
Sorry when it sound somewhat clumsy. I'm not an English native speaker (obviously). I'm always struggling with the documentation...

**Comment by DLFW** [comment]
@EvanCarroll : can this be closed? Are you still missing something or do you have any proposal?
