### ISSUE TITLE
[Feature Request] skim support

### ISSUE THREAD

**Issue by alvaro17f** [kamiyaa/joshuto#440]
Would it be possible to add [skim](https://github.com/lotabout/skim) for fuzzy finding?
Some people prefer skim instead of fzf.

Thanks in advance.

**Comment by Dzordzu** [comment]
It will be as soon as #446 is merged

**Comment by Dzordzu** [comment]
#446 landed in the main branch. Next release will provide a `custom_search` and a `custom_search_interactive` commands. Can you close the issue?

**Comment by alvaro17f** [comment]
Thank yo @Dzordzu
