### ISSUE TITLE
How to reset selection?

### ISSUE THREAD

**Issue by gh-xj** [kamiyaa/joshuto#453]
In ranger, `<c-r>` could be used to reset things, for example reset the files selection from visual mode, is there a equivalent in joshuto?

**Comment by DLFW** [comment]
Hi,
for the visual mode, it's just `escape` by default:
```
  { keys = ["escape"], commands = ["escape"] }
```
That's part of the default template.

For unselecting the “normal selection”, there is nothing in the default template but you can easily add a key-chord for that. I have this key-mapping for deselecting the “normal” selection:
```
  { keys = ["x"], commands = ["select --all=true --deselect=true"] }
```
