### ISSUE TITLE
Failed to parse keymap.toml

### ISSUE THREAD

**Issue by yongxingzhao** [kamiyaa/joshuto#458]
### Failed to parse keymap.toml

![image](https://github.com/kamiyaa/joshuto/assets/41985658/0b1b62f1-5834-4487-a8f1-2f07b10236ca)

default keymap.toml
version: 0.9.5

**Comment by yongxingzhao** [comment]
file path: ~/.config/jushuto/keymap.toml

**Comment by DLFW** [comment]
Hi, there was a breaking change after the release of 0.9.5. Either update your version to the current head-version from the repository or use the configuration template from version 0.9.5: https://github.com/kamiyaa/joshuto/tree/v0.9.5/config

**Comment by Dzordzu** [comment]
In case of #446 being merged this can work fine (again :) )

**Comment by yongxingzhao** [comment]
> Hi, there was a breaking change after the release of 0.9.5. Either update your version to the current head-version from the repository or use the configuration template from version 0.9.5: https://github.com/kamiyaa/joshuto/tree/v0.9.5/config嗨，0.9.5 发布后有一个重大变化。从存储库将您的版本更新为当前的头版本，或使用版本 0.9.5 中的配置模板： https://github.com/kamiyaa/joshuto/tree/v0.9.5/config

thanks

**Comment by yongxingzhao** [comment]
> In case of #446 being merged this can work fine (again :) )如果 #446 被合并，这可以正常工作（再次:) ）

🙏
