### ISSUE TITLE
Characters is not displayed normally

### ISSUE THREAD

**Issue by cybertheye** [kamiyaa/joshuto#462]
Steps:
1. brew install joshuto
2. ~ $ joshuto

then i get

<img width="289" alt="image" src="https://github.com/kamiyaa/joshuto/assets/91599174/3d58d855-eedb-43ba-92b2-5d3373a6540a">

Am i missing some configuration here?

**Comment by Dzordzu** [comment]
Yep. Your font does not support some chars. Try installing fallback font such as NerdFonts (`X`, `firacode`,  `firamono`, and `nerdfontssymbolsonly`) are enough
