### ISSUE TITLE
There will always be blue arrows in the left frame.

### ISSUE THREAD

**Issue by 0xnofoot** [kamiyaa/joshuto#470]
<img width="1680" alt="截屏2023-12-09 22 02 41" src="https://github.com/kamiyaa/joshuto/assets/108229781/e8bd7140-92a8-4738-a227-3a279257d4a4">

There will always be blue arrows in the left box, and as I switch between different software, the arrows will move up and down and more and more. I want to know what this is and how to get rid of these arrows.

Shown in the red box on the left

**Comment by DLFW** [comment]
How is this related to Joshuto?

**Comment by 0xnofoot** [comment]
This only happens when I use joshuto.

**Comment by kamiyaa** [comment]
What terminal are you using? Do the arrows persist between applications?

**Comment by 0xnofoot** [comment]
When I use iterm2, the arrows always appear randomly and slowly fill the left. This doesn't seem to be a problem on kitty, but I haven't tested any more examples.

**Comment by kamiyaa** [comment]
> When I use iterm2, the arrows always appear randomly and slowly fill the left. This doesn't seem to be a problem on kitty, but I haven't tested any more examples.

I also use iterm2 occasionally, but never ran into this before.
What kind of terminal apps are you opening with joshuto?

**Comment by 0xnofoot** [comment]
it happens when I just use joshuto

**Comment by kamiyaa** [comment]
https://stackoverflow.com/questions/38136244/iterm2-how-to-remove-the-right-arrow-before-the-cursor-line

Maybe this is related?

**Comment by 0xnofoot** [comment]
https://github.com/kamiyaa/joshuto/assets/108229781/419f8634-65f0-49da-9ac1-e9e5c53fa513

I record a video, watch the left side

**Comment by 0xnofoot** [comment]
Thank you very much, sorry for I don't search this issue, because I just met with joshuto.

thank you again, and I like your project.
