### ISSUE TITLE
Issue with copying filenames

### ISSUE THREAD

**Issue by MrXueBao** [kamiyaa/joshuto#476]
When copying the file name or directory names, I usually want to paste that path to some commands like cd or open. But if the path contains spaces like ~/My Folder1/My Folder2, this causes issue and inconvenience since I had to manually add \ before each space when running the command. Can you add this feature of including \ before spaces in file paths or make it configurable?

**Comment by kamiyaa** [comment]
You can put quotes around it

```
cd 'path/ with a space'
```
Hope this helps!

**Comment by MrXueBao** [comment]
ah this was helpful. sorry I made a mistake irrelevant with joshuto lol
