### ISSUE TITLE
quit --output-current-directory cannot be used normally

### ISSUE THREAD

**Issue by yjcup** [kamiyaa/joshuto#478]
I use joshuto on macos, use brew to install joshuto, and use the default configuration. However, quit --output-current-directory cannot be used normally. When pressing Q, it is still in the current folder.
<img width="551" alt="image" src="https://github.com/kamiyaa/joshuto/assets/75558384/334c8fba-3167-4a96-88d1-9232dc6af35e">
<img width="755" alt="image" src="https://github.com/kamiyaa/joshuto/assets/75558384/55d657e7-cfc5-4456-a569-ac2a889fc9cd">
<img width="569" alt="image" src="https://github.com/kamiyaa/joshuto/assets/75558384/c8e04fd9-1755-40e1-910a-0f341f12e5ee">

**Comment by kamiyaa** [comment]
You must add a function to bashrc, zshrc, etc.
as shown here:
https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md#quit-quit-joshuto

This is because a child process cannot change the pwd of a parent process
