### ISSUE TITLE
Add "--config" flag as a CLI argument

### ISSUE THREAD

**Issue by Lodobo** [kamiyaa/joshuto#479]
It would be useful in scripts to be able to start joshuto with a one-off config that is different from the system config. Being able to specify which config to load when you execute the program would be really great.

Something like this:

`joshuto --config="/path/to/config"`

I can see how it could be an issue since all the config files are separate. So maybe you could add an option to import the other config files from the main config?

**Comment by kamiyaa** [comment]
> I can see how it could be an issue since all the config files are separate. So maybe you could add an option to import the other config files from the main config?

maybe provide a `--config-dir` instead? all the files in that directory will be considered joshuto's config.

> It would be useful in scripts to be able to start joshuto with a one-off config that is different from the system config. Being able to specify which config to load when you execute the program would be really great.

Have you considered just changing the environment variables in your scripts to point to a different directory?

https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/README.md#configuration
