### ISSUE TITLE
Environment variable not found

### ISSUE THREAD

**Issue by fatualux** [kamiyaa/joshuto#480]
# Environment variable not found when I choose 'bulk rename'

## Steps to reproduce the issue

- I have a shortcut to start joshuto in my Sway config file

```
bindsym $alt+Control+a exec dunstify -r 333 "File Manager" && foot -e joshuto
```

- In my joshuto config file, in keymap.toml I have a new keymap for bulk rename:

```
 { keys = [ "b", "b" ],  command = "bulk_rename" },
```

## Expected behavior

Until three days ago, I would like to be able to rename multiple files at once with this command, but now, if I choose 'bulk rename' I get an error:

```bash
environment variable not found
```

If I open a shell, (using either ***foot*** or ***alacritty***) and launch Joshuto, the command will work as expected.

Unfortunately, I do not remember what I changed in my config files to cause this error.

Could you help me?

Thanks in advance,

FZ

**Comment by fatualux** [comment]
Uploading recording_2024-01-17_18:27:49.mp4…

**Comment by kamiyaa** [comment]
`bulk_rename` uses the `EDITOR` environment variable to determine what editor to use.

You may need to set this environment variable in your script for it to work.

Reference: https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md#bulk_rename-rename-all-selected-files

**Comment by fatualux** [comment]
Pardon my noobish, doubt, but I set this environment variable in my .bashrc

```bash
# Default apps

export BROWSER='firefox'
export VISUAL=vim
export EDITOR=vim
```

and in my sway config

```
# SET $mod key on SUPER
set $alt Mod1
set $mod Mod4
set $EDITOR vim
set $TERMINAL alacritty
```
but nothing changes, I cannot figure where I am to add the environment variable...

Plus, i do not understand whi this issue occur only when I start joshuto from sway with a shortcut
Thanks for your time and support

**Comment by kamiyaa** [comment]
You can try debugging it by changing `foot -e joshuto`

to `foot -e path/to/a/script`

inside the script:

```
#!/bin/bash

echo "EDITOR: $EDITOR"
```
and see if it prints anything.
If it does, then you can use this script to launch joshuto.
If not, then export it in the script

```
#!/bin/bash

echo "EDITOR: $EDITOR"

export EDITOR=vim

joshuto
```

**Comment by fatualux** [comment]
Thanks!

I fixed the issu by following your advice; i put this in my sway config:

```
bindsym $alt+Control+a exec dunstify -r 333 "File Manager" && export EDITOR=vim && foot -e joshuto
```
and now it works.
I missed the "export" of the variable.
Thanks again!
