### ISSUE TITLE
v0.9.7 - `Cargo.toml` does not match `Cargo.lock`

### ISSUE THREAD

**Issue by xrelkd** [kamiyaa/joshuto#514]
The version number in `Cargo.lock` is not matched with `Cargo.toml`.
https://github.com/kamiyaa/joshuto/blob/v0.9.7/Cargo.lock#L809

This leads to some package manager such as `nix` failed to update `joshuto`.
Because `nix` tries to use `--frozen` flag to ensure the package and its dependencies are reproducible.
Please remember to update `Cargo.lock` after bumping the version number in `Cargo.toml` and then make the git commit.

Maybe we can bump the version to `v0.9.8` to fix this issue.

**Comment by kamiyaa** [comment]
Done :+1:

**Comment by xrelkd** [comment]
Thanks. It works now.
BTW, the update for NixOS/nixpkgs is available here: https://github.com/NixOS/nixpkgs/pull/296281 .
