### ISSUE TITLE
Use of `--change-directory` command line argument?

### ISSUE THREAD

**Issue by BigBrotherJu** [kamiyaa/joshuto#519]
According to doc:

> - `--change-directory`: sets the quit behavior to change directory instead of noop when closing the last tab

When I invoke joshuto with `joshuto --change-directory`, and exit by pressing `q` in the last tab, my current working directory is not changed to the directory displayed in the first row of joshuto UI.

So how to use this option?

**Comment by kamiyaa** [comment]
Added link to docs.

Take a look at the function here: https://github.com/kamiyaa/joshuto/blob/main/docs/configuration/keymap.toml.md#quit-quit-joshuto

**Comment by kamiyaa** [comment]
Actually I think this argument is no longer available xd
