### ISSUE TITLE
How do I configure so that I'm not being asked 'open with'?

### ISSUE THREAD

**Issue by jerzybrzoska** [kamiyaa/joshuto#53]
Lets take for example `.html` files. How do I configure `mime.toml` so that they get opened like in [lf](https://github.com/gokcehan/lf), by the default browser.
Or more general, how do I configure `mime.toml` or any other of the configuration files, so that any file get opened by `xdg-open` with the command according to the settings in my OS. Setting `xdg_open = true` or to `xdg_open = false` in `joshuto.toml` does not change anything.

**Comment by kamiyaa** [comment]
It seems I accidentally removed the code for `xdg_open` a while back. Its been re-added in 314245d36f3ca7da9ce329513938b452a2c90f1d so it should be working now.

**Comment by jerzybrzoska** [comment]
Thanks. I just cloned the repo and compiled the code to find out whether it works and.. and since your last commit the arrows do not work ('no mapped input') Do arrows work on your PC?

**Comment by kamiyaa** [comment]
Yea, I've been making a lot of changes to how the configurations work.

`up/down/left/right` has been changed to `arrow_up/arrow_down/arrow_left/arrow_right` so its more clear.
(216ca0938f36476e221276f2f63d68bf8b9d770c)

See here as well: https://github.com/kamiyaa/joshuto/blob/main/config/keymap.toml#L39

Side note: I just changed the way `mimetype.toml` worked.
You can take a look at the [wiki](https://github.com/kamiyaa/joshuto/wiki/mimetype.toml) and the [config](https://github.com/kamiyaa/joshuto/blob/main/config/mimetype.toml)

**Comment by kamiyaa** [comment]
Feel free to reopen this issue if you still have problems

**Comment by jerzybrzoska** [comment]
All works very well now - files open without being prompted. Thank you for your contribution and support.
