### ISSUE TITLE
Directory chooser

### ISSUE THREAD

**Issue by devraza** [kamiyaa/joshuto#530]
Though `joshuto` has a file chooser (`--file-chooser`) this doesn't seem to work on directories. Ranger, however, apparently does support this (`--choosedir`). There should be an option to choose files *or* directories, which can be useful when selecting what directory a file should download to in qutebrowser, for example.

**Comment by DLFW** [comment]
Hi,
I have no idea how `--file-chooser` works; Joshuto lacks documentation on that.

But what works for me is to use a temp-file for the output (`joshuto --output-file /tmp/josh-selection`) and then quit Joshuto with `quit --output-current-directory` (which I have mapped to `Q`). Downside: It returns the directory you're _in_, not the one that is selected. I agree it's not great but it does the job for me.

Also agree that a straight-forward `--dir-chooser` would be a good enhancement. (And some docs for `--file-choose`.)
