### ISSUE TITLE
Feature request: implement scrollable preview area

### ISSUE THREAD

**Issue by Zeioth** [kamiyaa/joshuto#535]
It's amazing joshuto has `mouse_support = true` thank you so much for adding it.

If it also suppored scrolling the preview same as ranger I would definitely use it for my daily work.

**Comment by krivahtoo** [comment]
There is already a pr for this feature #527 It is yet to be reviewed and/or merged.

**Comment by Zeioth** [comment]
Thank you for the feedback. I'm gonna test it and write my feedback between tonight and sunday.

**Comment by Zeioth** [comment]
@krivahtoo I've built the fork and tested it on foot and alacritty, and scrolling over the preview area does nothing on my end.

I have
```toml
mouse_support = true
```

**Comment by Zeioth** [comment]
Actually I just noticed I was building the main branch by accident. `feat/preview-mouse-scroll` seem to work as expected.

**Comment by Zeioth** [comment]
I've uploaded a video comparing it with ranger too. Everything seems fine. The sensibility also seems to be really good on both my scrollwheen and mini-trackball.

https://www.youtube.com/watch?v=CjKcNoJ9VF4

**Comment by kamiyaa** [comment]
> There is already a pr for this feature #527 It is yet to be reviewed and/or merged.

I must've missed this. will take a look now!
