### ISSUE TITLE
symlink not work on macos

### ISSUE THREAD

**Issue by awayme** [kamiyaa/joshuto#544]
I recently started using Joshuto after switching from Ranger.py. 
Everything in Joshuto works like a charm, but I’m having an issue with creating symlinks.

Here’s what I’m doing:

	•	Using Joshuto 0.9.8 with the default configuration pulled from the GitHub repo’s main branch (no changes made to the configs).
	•	I press ‘yy’ on a file or directory, then navigate to a new directory and press ‘pL’ or ‘pl’.

However, nothing happens. No symlink is created and no error is reported.

Is there something I’m doing wrong, or is this a known issue?

Details:

	•	Joshuto version: 0.9.8
	•	Build time: 2024-03-15 23:53:29 +00:00
	•	Build environment: rustc 1.76.0 (07dca489a 2024-02-04) (Homebrew)

	•	System: macOS M1 / Sonoma 14.5

Thank you!

**Comment by kamiyaa** [comment]
Hey, I think theres some confusion here with the symlink ability.

It should be
1. `pl` add selected files to clipboard
2. `pp` paste them as symlink

Similar to how cut and copy works

cut: `dd, pp`
copy `yy, pp`

**Comment by kamiyaa** [comment]
Interesting.
I think the `ranger` approach makes more sense. Intuitively, users would `yy` and decide whether to paste, paste symlink or paste overwrite at a later state.

Lets create a separate issue for this :+1:
