### ISSUE TITLE
francoiscabrol/ranger.vim like plugin for vim?

### ISSUE THREAD

**Issue by GopherJ** [kamiyaa/joshuto#555]
Hi, I saw joshuto is faster than ranger, would like to use it as an alternative but in neovim. Is there a plugin available?

**Comment by DLFW** [comment]
Like this?: https://github.com/theniceboy/joshuto.nvim

**Comment by micsama** [comment]
网址：https://github.com/theniceboy/joshuto.nvim
this is good
