### ISSUE TITLE
joshuto hangs on interactive commands

### ISSUE THREAD

**Issue by flipsi** [kamiyaa/joshuto#569]
If I run interactive commands like `:bulk_rename`  or `:shell trash-restore`, joshuto will hang and not respond anymore.
The commands execute (i.e. I can open an editor, use it, and are prompted about the rename or prompted about which file to restore respectively), but after confirming with `y` / pressing a number, joshito does not resume. 

I can only interrupt (Control-c), which causes joshito to exit. The desired effect (file renaming or restorement) does not happen.

I do not understand what exactly is happening yet.  FWIW in ranger, the trash restore does work as expected, but the bulk rename is also broken.

Any help is appreciated.

**Comment by kamiyaa** [comment]
What OS and terminal are you using?

**Comment by flipsi** [comment]
> What OS and terminal are you using?

Sorry, I should have added this immediately.

```
> cat /etc/issue
Arch Linux \r (\l)

> uname -a
Linux frey 6.11.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 17 Oct 2024 20:53:41 +0000 x86_64 GNU/Linux

> alacritty --version
alacritty 0.13.2 (bb8ea18e)

> fish --version
fish, version 3.7.1

> joshuto --version
joshuto-0.9.8
tag:v0.9.8
commit_hash:2a392e85
build_time:2024-03-15 23:57:34 +00:00
build_env:rustc 1.76.0 (07dca489a 2024-02-04),

**Comment by kamiyaa** [comment]
Does this still happen with latest git version?

**Comment by flipsi** [comment]
> Does this still happen with latest git version?

To my suprise/delight, *no*, it doesn't! 

Care to explain what fixed it? :laughing:  

Thank you regardlessly!
