### ISSUE TITLE
Rework copy-paste mechanism

### ISSUE THREAD

**Issue by kamiyaa** [kamiyaa/joshuto#575]
Original thread: https://github.com/kamiyaa/joshuto/issues/544#issuecomment-2426252447

As stated, the ranger UX is probably more intuitive from a design perspective and from users migrating from ranger

Would love to hear what others have to say on this

**Comment by flipsi** [comment]
Exactly my thinking, the ranger approach would be more consistent and intuitive.

Thanks for creating this (separate) issue!

**Comment by kamiyaa** [comment]
Closed via 928f9f37c7ae5c96bd4b4f0a25196ad2734fda1f
