### ISSUE TITLE
A problem about image preview

### ISSUE THREAD

**Issue by Zaire404** [kamiyaa/joshuto#583]
![image](https://github.com/user-attachments/assets/ffbfe4a7-c385-4260-a5e8-a6f3d7e46573)
Why is my image preview blurry?
The preview _file.sh says "Image previews are independent from this script".
So I dont know how to solve it.
I use Alacritty and nomacs.

**Comment by DLFW** [comment]
[Terminal](https://github.com/benjajaja/ratatui-image?tab=readme-ov-file#compatibility-matrix)?

**Comment by Zaire404** [comment]
> [Terminal](https://github.com/benjajaja/ratatui-image?tab=readme-ov-file#compatibility-matrix)?

I use Alacritty.

**Comment by DLFW** [comment]
I don't use Alacritty, but looking at the table I [have linked](https://github.com/benjajaja/ratatui-image?tab=readme-ov-file#compatibility-matrix), I guess that explains your observation. Maybe some other Alacritty user here knows more?

If Alacritty is the reasons here (what I would expect), your only chance for better images is to go the hard way and use an external preview mechanism like explained [in the docs](https://github.com/kamiyaa/joshuto/tree/main/docs/image_previews#thumbnails-via-external-scripts). Of course, you could also switch your terminal if that's an option for you.

**Comment by Zaire404** [comment]
> course

Thanks, Alacritty is the reason, so I am ditching Alacritty for Kitty.
