### ISSUE TITLE
Hidden files are traversing the column.

### ISSUE THREAD

**Issue by alannssantos** [kamiyaa/joshuto#59]
# It happens only files, hidden folders behave correctly.

![Captura de tela_2021-05-21_18-46-44](https://user-images.githubusercontent.com/16065736/119201486-65f5c180-ba65-11eb-983c-5ef495b01e04.png)

**Comment by kamiyaa** [comment]
Fixed via 7ef22c23c21db754a1321e7b23376615367527a3
