### ISSUE TITLE
Add a method to use configurations while running as root with `sudo`

### ISSUE THREAD

**Issue by domeniczz** [kamiyaa/joshuto#592]
when running joshuto as root `sudo joshuto`, it does not use the custom configurations.

**Comment by Canvis-Me** [comment]
`sudo -E joshuto`

**Comment by domeniczz** [comment]
ah, sorry about the stupid question.

**Comment by DLFW** [comment]
> ah, sorry about the stupid question.

@domeniczz No, don't be sorry. Just in case we had a misunderstanding: I did not mean that your question was stupid, but that **my** question back to you was just an absurd thought and maybe unnecessary. Bad and confusing wording from my side. Sorry, for that! I should be more careful when communicating in a non-native language.
