### ISSUE TITLE
file deletion asks for capital Y for confirmation but reacts on lowercase y

### ISSUE THREAD

**Issue by DLFW** [kamiyaa/joshuto#68]
When deleting a file (dD), joshuto asks:
```
Delete 1 files? (Y/n)
```
which indicates that only a capital Y confirms deletion. Instead, a capital Y aborts deletion but instead a lowercase y confirms the deletion.

Is it a spelling mistake in the prompt or is the check implemented wrong? What's the desired behavior?

**Comment by LovecraftianHorror** [comment]
The general rule of thumb for prompts like that is that the capitalized option represents the default so I would assume that inputting nothing would also delete.

However, I do think that Y should be accepted as y and N as n

**Comment by DLFW** [comment]
Oh, yes. Just saw that ranger asks with (y/N). Never recognized that. (BTW, "no" as default somehow makes more sense to me... anyway, different story...)
Thanks!
