### ISSUE TITLE
For me, It's kind of lagging

### ISSUE THREAD

**Issue by python128** [kamiyaa/joshuto#73]
Try to make it faster?
I would appreciate it. Also, may I know why it is lagging?

**Comment by kamiyaa** [comment]
Can you provide some more information? Like what OS you are running, what use case you are using it for (local fs, nfs, mtpfs, etc). Is it slow all the time or for certain situations?

Thanks 👍

**Comment by python128** [comment]
I'm using WSL with Ubuntu. My present editor is Kakoune. 
Say, If I want to make it go down a long list of files and/or directories, and press and hold the down/up arrow key, then it lags.

**Comment by DLFW** [comment]
Hmmmmm.... Maybe one observation from my side:

I have never seen Joshuto being slower than any other fm, but one thing that might give the impression of being slow and could be enhanced anyway is that Joshuto seems to "queue" the key presses. Now, if one scrolls through the entries of a directory and IO is not fast enough, the scroll-down key-pressed ( j's ) seem to get buffered. When the user then releases the key, the cursor continues moving and "works off" the queued key-presses. So it might feel like Joshuto is reacting late or "running behind".

A better behavior would be that Joshuto always stops scrolling immediately when the user releases the key.

@python128, is it possible that that's the  behavior you're talking about?

**Comment by python128** [comment]
Yup. The same behavior. Is there any way, to like, not buffer?
My directories usually have a lot of files, so it would be helpful.
Thanks in advance.

**Comment by kamiyaa** [comment]
I will say I've experienced this on an older laptop (Thinkpad T420) running WSL.
However, I wasn't able to reproduce it on my current system.
This does sound like an IO bottleneck of some sort.

You can try the current dev branch to see if that fixes it.
Directory loading got pushed onto a separate thread, which should make input more responsive.
