### ISSUE TITLE
Show Keybindings when pressing <?>

### ISSUE THREAD

**Issue by JacobTravers** [kamiyaa/joshuto#84]
Most TUI programs have a useful list of categorized keybindings that shows when `<?>` or `shift`+`/` are pressed to quickly check which-key does X, or see what commands are available to the user. I believe this is a low-input/high-return improvement for all new users. This would also make the project feel much more polished.

**Comment by Vinegret43** [comment]
I'm currently working on this issue and have already implemented about 60% of it. Just need to add formatting and grouping to make help page look decent and refactor my code in places where it's necessary, so  think i'll open a pull request in a few days. Posting this just to avoid work duplication if someone also wants to work on this issue
