### ISSUE TITLE
Rclone mounted directories suddenly slower?

### ISSUE THREAD

**Issue by JacobTravers** [kamiyaa/joshuto#86]
Hey I'm not sure what's happening but when I try to use Joshuto inside an rclone mounted (google drive) directory it becomes extremely slow. If I start Joshuto from another directory and navigate into my mounted directory it gets bogged down as well. This used to work fine before.

I think it may have to do with [this commit](https://github.com/kamiyaa/joshuto/commit/a4b4a1b4b9c7827f756e9950d73dc885d2954ff9). Rclone only lists files and directories as needed, and I'm guessing Joshuto is trying to recurse through child directories and figure out the size of each directory which would be extremely slow because it's a large directory tree with tons of files that all need to be accessed through an api. As a control I used pcmanfm which worked fine in the same directories.

**Comment by kamiyaa** [comment]
Yeah, I was afraid of this performance regression as well.

One way ranger does it is by having the option to toggle this behaviour:
https://github.com/ranger/ranger/blob/f1f3f1765f6e97b4e1af80da8f237bf7f1ad895f/ranger/config/rc.conf#L52

I think we can expand on this solution by having 3 options:
1. No directory counting
2. Lazy directory counting
only count when a preview has been cached/loaded
3. Full directory counting
This will traverse directories to count files

**Comment by kamiyaa** [comment]
Added `automatically_count_files` option in 97ca1fb6d44de66d872422783c38ae198b0edfb9.

This currently disables file counting all together and should improve performance on network mounts, mtp, etc.

Future plan is to make it opportunistic. ie. if we already have that directory loaded into memory, then getting the count is trivial.

I will close this issue when that is completed.

**Comment by kamiyaa** [comment]
Support has been added to lazily count directory items:
The contents will only be accounted for if the directory contents has already been loaded into memory.

Some minor problems we will need to fix in the future is updating this value whenever a directory reload is executed.

commit: c7053df125a6943786f412348d85324e926e5ba5
