### ISSUE TITLE
Command to exit and change CWD

### ISSUE THREAD

**Issue by JacobTravers** [kamiyaa/joshuto#88]
I would like to add a feature request so that pressing a key-binding like `<alt> + <return>` will exit and CD to the current directory in Joshuto.

**Comment by kamiyaa** [comment]
You can currently do this via an alias:
```bash
alias joshut='joshuto --lastdir /tmp/$USER/joshuto-lastdir;
	LASTDIR="$(cat /tmp/$USER/joshuto-lastdir)";
	[ "$LASTDIR" != "$(pwd)" ] && cd "$LASTDIR"';
```
This is not optional though; you will always cd to the current directory in Joshuto on exit.
But you can go back with `cd -`

If you want it to be optional, we can potentially modify the exit code to indicate to our shell that we want to move to the specified directory. ie. exit code 2 means cd to the current directory in Joshuto

**Comment by JacobTravers** [comment]
Hmm that sounds sort of hacky, maybe this function from hunter might be helpful in finding a solution:
https://github.com/rabite0/hunter/blob/355d9a3101f6d8dc375807de79e368602f1cb87d/src/file_browser.rs#L931

**Comment by kamiyaa** [comment]
Yea, we can implement a command like hunter to `QuitToCwd`.

Then have a bash function to facilitate it like hunter. This is what I currently have atm:
```bash
function joshuto() {
	CWD_FILE="/tmp/$USER/joshuto-cwd"
	env joshuto --lastdir "$CWD_FILE" $@

	if [ -e "$CWD_FILE" ]; then
		JOSHUTO_CWD=$(cat "$CWD_FILE")
		rm "$CWD_FILE" && cd "$JOSHUTO_CWD"
	fi
}
```

I will be adding `QuitToCwd` shortly.
I don't think I will be adding all the additional options hunter has (at least for now) just because I don't think it will work well with files with spaces or other special characters (without more work).
ie.
```bash
HUNTER_CWD=...
F=...
MF=...
```

We can also move `--lastdir` into an option in the config instead of a command line parameter, but that can be for the future

**Comment by kamiyaa** [comment]
new command added: `quit_to_cwd`
This will write the current directory to a file specified by the `--lastdir` command line option.
Then the function I mentioned above will go to that directory upon quiting joshuto

commit: f8851c7f9ac22289e473a2911611958e361befdc

**Comment by JacobTravers** [comment]
This is excellent! The only change I would make (and I don't mean to be nitpicky) would be to change the name from `--lastdir` to `--last-dir` just to separate the two words and keep a regular naming-convention for flags. Maybe we could add a shorthand version `-l` as well, if we want to type less. Thank you again and I appreciate the quick turnaround!

**Comment by kamiyaa** [comment]
changed to `--last-dir` in dev branch fcf869c4338faeeb146963e7aeae394b2e7b4dcb.

I've decided to not add `-l` just because I think it might be used for a different option in the future and `--last-dir` seems like a non-intuitive option to have a shorthand version for.
